= Lee Yu Cong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLInic

== Introduction
Hello, I am Yu Cong. I am currently studying Computer Science as my major in the School of Computing, National University of Singapore.
I formed a team with 4 other students to create CLInic as part of the project requirement under the CS2103T module as part of my university education.

// write clearly this is to showcase contributions
This project portfolio serves to document my contributions to this project. You can see my contributions to
the <<Summary of contributions, code contribution>>, the <<Contributions to the User Guide, user guide>> and the <<Contributions to the Developer Guide, developer guide>> below.

CLInic is a desktop application made for clinics who wish to automate their daily operations.
The CLI in CLInic is an acronym for Command Line Interface, which is the main method to use this application.
Unlike traditional address books, the doctor or clinic receptionist can easily find patient or medicine information by entering one simple line in the command box.
You can also manage patient and medical records easily with the easy-to-use CLinic.

// list of main features
Examples of the main features include:

. Efficient management of patient and medicine information
. Realistic model of clinic's daily operation and commands to cater to clinics.
. Customised receipts, medical certificates and referral letters for different clinics.

== Summary of contributions
//preface to this section to inform reader purpose of this section
In this section, you can find the major and minor enhancement that I made to CLInic:

* *Major enhancement*: Implementation of *medical records in CLInic*
** What it does: It allows the clinic to keep track of medical stocks in the clinic.
** Justification: The medical stocks are managed and the useful commands can organise and find the information of a medicine.
** Highlights: With a simple command, you can easily list out all medical stocks that are low in stock.

* *Minor enhancement*:
** Rewrote command output to make it more user friendly.

// not yet done
* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

* *Other contributions*:
** Wrote the utilities for test cases for other members to build their tests upon.
** Proof-read all code written to adhere to standard Java writing style.
** Advised my team to apply knowledge learnt in lecture wherever necessary.
** Reviewed pull requests : https://github.com[#27], https://github.com[#31], https://github.com[#107]


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=medicine]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=medicine]
