= Afiq Lattif - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoURL: https://github.com/CS2103-AY1819S1-W16-2/main


== PROJECT: SocialCare

:sectnums:
== Overview

This portfolio records my contributions to the SocialCare project, under the CS2103T Software Engineering module offered by the School of Computing in NUS.

SocialCare empowers volunteer managers to revolutionise the way they manage their resources. With features such as Statistics and Exporting of Certificates with a simple command, the organisational process has never been as effective.

With my role as a Developer for this project, I implemented *volunteer management functions*, ensuring that the organizational process is simpler yet systematic.

== Summary of contributions

My contributions to the project mainly focuses on volunteer management.

* *Major enhancement*: Added *commands to manage volunteers*
** What it does: Allows the user to manage volunteer details with commands such as add, edit and delete.
** Justification: Streamlines the management of volunteers to fit the volunteer organisation context
** Highlights: Affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands by implementing additional fields and checks.

* *Minor enhancement*: Added a Birthday util that exports birth date to a readable format and checks if birth day is before current date.

* *Code contributed*:
Here is a https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=afiqlattif[link]
to my code on the Project Code Dashboard.

* *Other contributions*:

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: link:https://github.com/CS2103-AY1819S1-W16-2/main/pull/173[#173]
*** Revised content in the Developer Guide: link:https://github.com/CS2103-AY1819S1-W16-2/main/pull/72[#72], link:https://github.com/CS2103-AY1819S1-W16-2/main/pull/121[#121]
** Community:
*** Reviewed PRs for team members (with non-trivial comments) : link:https://github.com/CS2103-AY1819S1-W16-2/main/pull/144[#144], link:https://github.com/CS2103-AY1819S1-W16-2/main/pull/174[#174]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=volunteermanagement]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=command-add]

