= Afiq Lattif - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoURL: https://github.com/CS2103-AY1819S1-W16-2/main


== PROJECT: SocialCare

:sectnums:
== Overview

This portfolio records my contributions to the SocialCare project, under the CS2103T Software Engineering module offered by the School of Computing in NUS.

SocialCare is a volunteer management system that allows Social Welfare Organisations to streamline the process of managing their volunteers and events.
The user interacts with it by through typing commands in the application, and it has a Graphical User Interface (GUI) to organise their information more systematically.


== Summary of contributions

My contributions to the project mainly focuses on volunteer management.

* *Major enhancement*: Added *commands to manage volunteers*
** What it does: Allows the user to manage volunteer details with commands such as add, edit and delete.
** Justification: Streamlines the management of volunteers to fit the volunteer organisation context
** Highlights: Affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands by implementing additional fields and checks.

* *Minor enhancement*: Added a Birthday util that exports birth date to a readable format and checks if birth day is before current date.

* *Code contributed*: [https://github.com/CS2103-AY1819S1-W16-2/main/tree/master/src/main/java/seedu/address/model/volunteer[Functional Code]] [https://github.com/CS2103-AY1819S1-W16-2/main/tree/master/src/test/java/seedu/address/model/volunteer[Test Code]]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=volunteermanagement]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=command-add]

