= Ng Zhen Wei Alec - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: SousChef

---

== Overview

Souschef is a desktop smart cooking sidekick, offering personalised guidance every step of the way. From recipe
recommendations just for you, to meal planning and inventory management, SousChef has everything you need to improve
life in the kitchen. +

Our users interact via CLI and GUI created with JavaFX. Written in Java, experience what many are enjoying.

== Summary of contributions

* *Major enhancement*: overhauled *the entire storage*
** This change allows the team to easily implement their functionality with much more ease.
** Justification: This enhancement improves the product significantly because it allows the other functions to work jointly
** Highlights: Without this the other components will not have functionalities to access their individual xml file.
** https://github.com/CS2103-AY1819S1-W10-4/main/pull/52[PR#52]

* *Major enhancement*: Health plan segment of Souschef
** This change allows new added on functionality and usage for the users of Souschef as the users are now able to view their
calories intake based on the meals they planned for themselves. Allowing them to make more informed decisions about
their food choices.
** Justification: This improve the product with the newly added on functionality.
** Highlights: Allow users to view their calories overview with a simple command along with graphic for easy understanding.
** https://github.com/CS2103-AY1819S1-W10-4/main/pull/72[PR#72], https://github.com/CS2103-AY1819S1-W10-4/main/pull/77[PR#77]
,https://github.com/CS2103-AY1819S1-W10-4/main/pull/139[PR#139], https://github.com/CS2103-AY1819S1-W10-4/main/pull/213[PR#213]



* *Bug fix* : solved bug issue when system will function when xml files are not found
** This change allows the system to bootup normally when any of the xml files are not found. Uses sampleData to start up.
** Justification: This improves the user experience
** Highlights: Without this change, the user experience would be drastically different as the system will not function properly.
** https://github.com/CS2103-AY1819S1-W10-4/main/pull/135[PR#135]


* *Other contributions*:

** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-W10-4/main/pull/58[#58],
https://github.com/CS2103-AY1819S1-W10-4/main/pull/151[#151]
*** Reported bugs and suggestions for other teams in the class
(examples: https://github.com/CS2103-AY1819S1-T13-3/main/issues/82[1])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===


include::../DeveloperGuide.adoc[tag=healthplan]

include::../DeveloperGuide.adoc[tag=storage]
