= Alex Koh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CAPTracker

---

== Overview

_CapTracker_ is a desktop application. The user interacts with it using a CLI,
and it has a GUI created with JavaFX. It is written in Java, and has about 10
kLoC.

== Summary of Contributions

* *Major Enhancements*: added *the ability to add, edit, and delete modules*.
** *What it does*: Allows the user to add, edit, and delete modules in CAPTracker one at a time. name-value paired (-name value) arguments instead of prefix used.
** *Justification*: Adding, editing, and deleting is needed to populate the CAPTracker. The name-value pair is also more intuitive for advance CLI users
** *Highlights*: name-value pair format was used as advance users are more familiar with it. The way the arguments are tokenize has also been changed.

* *Minor enhancement*:
*** Make improvements to the APIs: `CommandUtil.java`, `ParserUtil.java`, and `UniqueModuleList.java`
* *Code Contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=alexkmj[Project Code Dashboard - alexkmj]

* *Other contributions*:

** `Morphing`: Morphed the `Logic` and `Model` component including its unit test. Introduced the `Module` package.

** *Organization setup*: Created and setup GitHub team organisation.

** *Repository setup:* Setup organisation repository. Enable AppVeyor, Codacy, Coveralls, Travis CI, and GitHub Pages and its badges. Create team PR.

** *Manage releases*

** *Community*
*** PRs reviewed: https://goo.gl/QqNNsj[#23], https://goo.gl/6Wy8o4[#62], https://goo.gl/szTgtm[#71], https://goo.gl/SsxRkG[#76], https://goo.gl/rrR4bv[#106]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=add]

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=delete]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=designlogic]
