= Amabel Yeo - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoURL: https://github.com/CS2103-AY1819S1-W16-2/main/pull

== PROJECT: SocialCare

:sectnums:
== Overview

This portfolio page documents my involvement in SocialCare, a project done as part of the CS21303T Software Engineering module taught in NUS.

SocialCare is a desktop application made for social welfare organizations.
The application is designed to help manage volunteers and events effectively.
Users interact with the application using a Command Line Interface (CLI).
In addition, SocialCare has a Graphical User Interface (GUI) to display information in a user-friendly manner.

My role as a developer for SocialCare is to implement *record management functions*, which enables users to do the following:

* Assign volunteers to event
* Update volunteering records for volunteers
* Delete volunteering records of volunteer

== Summary of Contributions

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Set up the team repository on GitHub
*** Assigned and tracked project tasks
*** Ensured that project deliverables are done on time and in the right format
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: link:{repoURL}/76/[#76], link:{repoURL}/129/[#129]
*** Rewrote the quick start section of the User Guide: link:{repoURL}/154/[#154]
*** Revised content for the Logic component in the Developer Guide: link:{repoURL}/93/[#93]
** Community:
*** Reviewed PRs for team members (with non-trivial review comments): link:{repoURL}/58/[#58], link:{repoURL}/109/[#109], link:{repoURL}/114/[#114]
** Tools:
*** Integrated Travis to the Github repository

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=command-switch]
include::../UserGuide.adoc[tag=command-record]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=command-switch]
include::../DeveloperGuide.adoc[tag=command-manage]

