= Arsalan Cheema  - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ClinicIO

---

== 1. Overview
// command line constraint
// 2 paragraphs
// number sections
// pdf
This page showcases my contributions to an open source software engineering group project as part of a university module.
ClinicIO is a desktop application intended for medical clinic receptionists and doctors. It allows them to effortlessly
manage a multitude of clinic processes such as managing queues. While there is a Graphical User Inteface (GUI) for
displaying results, a key constraint for the module was to ensure that the application is used through a text interface.
The program logic is written in Java in an Object Oriented manner and the GUI is written in JavaFX.

In the management of the project, I was responsible for ensuring the quality of the project's documentation. This
involved a decided focus on reviewing language, ensuring that it is in-depth and simple to understand. I believe this is
important to enable our program to be adopted by users and external developers.

My individual role was as a developer in charge of managing the program's data. To this end, I worked together with my
group members to understand their features and subsequently integrated the ability to view analytics for each of them.
In addition, I contributed the ability to export data out of the program.

== 2. Summary of contributions

This section lays out my contributions to the project.

* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=arsalanc-v2[my code]

==== 2.1 Major enhancement: the ability to view detailed statistics and visualizations.
** _What it does_: It allows the user to track the activity of a clinic through objective metrics, in a simple manner.
Analytics are enabled for patients, appointments and doctors.
** _Justification_: This feature improves the product significantly because it provides a user with insight to make
decisions regarding the clinic's processes. This can be used to improve the efficiency and the experience for both staff
 and patients. It ensures that the clinic is able to improve with time, in order to benefit all stakeholders.
** _Highlights_: This enhancement integrates across the major functions of a clinic. It was a challenge to design and
implement a flexible yet powerful interface through which different types of visualizations can be easily created. A
consistent and visually appealing graphical user interface was also a key part of this. This was done in order to
ensure that many more metrics can be programmed to be tracked in the future.

The following code snippet adds a summary of statistics to be displayed:

`statData.updateSummary("title goes here", "list of labels go here", "list of values go here")`

* *Minor enhancement*: the ability to export various types of patient data to a human editable format (CSV).
// * *Minor enhancement*: a representation of a doctor-patient consultation with fields such as the patient's arrival
// time.

==== 2.2 Other contributions:

** Project management:
*** Added handy git tips that helped group members:
https://github.com/CS2103-AY1819S1-W14-1/main/projects/1#card-13922007[1],
https://github.com/CS2103-AY1819S1-W14-1/main/projects/1#card-13903185[2]

** Enhancements to existing features:
*** Added the ability to switch between GUI panels on top of an existing GUI placeholder:
https://github.com/CS2103-AY1819S1-W14-1/main/pull/227[#227]
** Documentation:
*** Updated the developer guide appendices: https://github.com/CS2103-AY1819S1-W14-1/main/pull/20[#20],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/61[#61]
*** Added a section to guide users on previewing user interfaces:
https://github.com/CS2103-AY1819S1-W14-1/main/pull/120/files[#120]
** Community:
*** Reviewed team mates' code contributions (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-W14-1/main/pull/60[#60],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/132[#132],
https://github.com/CS2103-AY1819S1-W14-1/main/pull/140[#140]
// https://github.com/CS2103-AY1819S1-W14-1/main/pull/144[#144],
// https://github.com/CS2103-AY1819S1-W14-1/main/pull/152[#152],
// https://github.com/CS2103-AY1819S1-W14-1/main/pull/179[#179],
// https://github.com/CS2103-AY1819S1-W14-1/main/pull/238[#238]

*** Reported bugs and suggestions for other teams in the cohort:
https://github.com/CS2103-AY1819S1-W13-2/main/issues/148[1],
https://github.com/CS2103-AY1819S1-W13-2/main/issues/157[2],
https://github.com/CS2103-AY1819S1-W13-2/main/issues/163[3]
// https://github.com/CS2103-AY1819S1-W13-2/main/issues/167[4],
// https://github.com/CS2103-AY1819S1-W13-2/main/issues/170[5]

== 3. Contributions to the User Guide

|===
|_The following are sections I contributed to the User Guide. They showcase my ability to write documentation targeting
end-users
._
|===

include::../UserGuide.adoc[tag=analyticscommands]

You can view my user guide contribution towards the export feature here:
https://github.com/CS2103-AY1819S1-W14-1/main/blob/master/docs/UserGuide.adoc#exporting-patient-data[exporting patient data]

== 4. Contributions to the Developer Guide

|===
|_The following below are sections I contributed to the Developer Guide. They showcase my ability to write technical
documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=analytics]

include::../DeveloperGuide.adoc[tag=export]



