= Bark HyeHyeon - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Souschef

---

== Overview

Souschef is a desktop smart cooking sidekick, offering personalised guidance every step of the way. From recipe
recommendations just for you, to meal planning and inventory management, SousChef has everything you need to improve
life in the kitchen. +

Our users interact via CLI and GUI created with JavaFX. Written in Java, experience what many are enjoying.

== Summary of contributions (To be updated...)
* *Major enhancement*: added *the ability to manage ingredients*
** What it does: Allows the user to track the stock of ingredients, view recipe according to ingredient and check
shop amount.

** Justification: This is a practical feature which would enhance user experience of cooking preparation.

** Highlights: Rather than mere stock tracking, this feature contains functions providing cognitive
shortcut for users. Also, it enables proper integration between information related to ingredient and recipe.

* *Major enhancement*: restructured *entire logic component*
** Justification: This was necessary to enable integration across multiple features, while maintaining efficiency by
distinguishing shared processes and making use of general classes.
** Highlights: This enables both modularization and efficient integration of features.
** https://github.com/CS2103-AY1819S1-W10-4/main/pull/64[PR#64]

* *Other contributions*:

** General/Team Enhancements:
*** Implementation of universal commands (Pull requests
https://github.com/CS2103-AY1819S1-W10-4/main/pull/66[#66])
*** Fix UI for desired view (Pull requests
https://github.com/CS2103-AY1819S1-W10-4/main/pull/151[#151])

** Community:
*** PRs reviewed (mainly related to logic component):
https://github.com/CS2103-AY1819S1-W10-4/main/pull/72[#72],
https://github.com/CS2103-AY1819S1-W10-4/main/pull/77[#77]
*** Reported bugs and suggestions for other teams in the class (examples:
https://github.com/CS2103-AY1819S1-F10-2/main/issues/240[1], https://github.com/CS2103-AY1819S1-F10-2/main/issues/225[2],
https://github.com/CS2103-AY1819S1-F10-2/main/issues/195[3], https://github.com/CS2103-AY1819S1-F10-2/main/issues/190[4], https://github.com/CS2103-AY1819S1-F10-2/main/issues/182[5])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
