= Benedict - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Piconso



== Overview

This portfolio seeks to document my contributions to our team’s project, Piconso. Piconso is an CLI
(Command Line Interface) Image Editor designed and developed for quick and efficient image-editing on your Desktop.
All traditional image-editing features can be performed solely through text commands, removing the hassle of
working with a mouse. Piconso does not only benefit the power users but also serves as a learning platform for new users
with its simple command line tools.

Below is a list of main features of our application:

* Several traditional image-editing features such as rotate, blur etc.
* Capability to define own custom transformation set.
* Direct access to images on Google Photos (download and upload).


== Summary of contributions
|===
|_This section summarises the implementations and contributions I've made for this project._
|===

=== *Major Enhancement* -- Ability to traverse into different directories

As majority of users have their images stored in different folders within their system drive, we decided to implement
a feature that would ease users' access to this images. Therefore, I have added the `cd` feature which allows
users to access these images without the need to store all their images to a specified folder for access.

** Highlights: To improve user's performance, I have coupled the `cd` feature with the implementation of the `Tab` function
which would auto-completes the user input with an existing directory in the current folder.

=== *Major Enhancement* -- Ability to open images for editing

Before any user could start editing an image, they would first need to open the image for editing. As such, the `select`
feature in AB4 was refactored and modified to the `open` feature we have here on Piconso. This feature allows users into
open an image from the current batch to be displayed on the GUI before any edits are made.

** Highlights: This enhancement requires in depth analysis of design alternative to ensure maximum efficiency in
retrieving images from the current directory.

=== *Minor Enhancement* -- Ability to traverse between image batches

As Piconso accesses only 10 images at any one time, the `next` and `prev` feature enables the user to access other
images within the same directory. This feature facilitate the ease of traversal of all the images within the current
directory.

=== *Code contributed* -- [https://github.com/CS2103-AY1819S1-T09-3/main/commits?author=benedictcss[All commits]] [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=benedictcss[Project Code Dashboard]]

=== *Other contributions*:

Below are other contributions that I have made for this project.

==== Project Management:
* Created labels, milestones and issues for issue tracking on GitHub
* Participated in tagging issues and merging/reviewing PRs
* Set up appveyor build, coveralls and reposense config file on Github.

==== Documentation:
* Added detailed implementation documentation for the directories command in Developer Guide, including diagrams: https://github.com/CS2103-AY1819S1-T09-3/main/pull/213[#213]
* Updated diagrams for Logic, Model and UI component. https://github.com/CS2103-AY1819S1-T09-3/main/pull/174[#174]

==== Enhancement to existing features:
* Updated the icon of the application. https://github.com/CS2103-AY1819S1-T09-3/main/pull/111[#111]
* Wrote additional test for existing features. https://github.com/CS2103-AY1819S1-T09-3/main/pull/107[#107]

==== Community:
* PRs reviewed: https://github.com/CS2103-AY1819S1-T09-3/main/pull/56[#56]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide.
They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=dir]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide.
 They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=cd]

include::../DeveloperGuide.adoc[tag=open]

include::../DeveloperGuide.adoc[tag=nextprev]
