= Benn Tay Guobin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: SousChef

---

== Overview

Souschef is a desktop smart cooking sidekick, offering personalised guidance every step of the way. From recipe recommendations just for you, to meal planning and inventory management, SousChef has everything you need to improve life in the kitchen.

Our users interact via CLI and GUI created with JavaFX. Written in Java, experience what many are enjoying.

== Summary of contributions
* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=benntay[Functional
code]]
* *Major enhancement*: added the _Meal Planner feature_.
** What it does: Allows users to add their desired recipes to a Meal Planner so that they can plan their days' meals.
** Justification: This feature improves the product significantly because a user can not only browse recipes, but also keep a record of the recipes they want to try on which specific days.
** Highlights: This enhancement was originally unsupported by the AB4 code; it is a completely new component feature.

* *Major enhancement*: restructured and modularised UI component and implemented panel
switching between different features.
** Justification: This was to allow easy and efficient integration for the UI aspect
across multiple features through the use of general classes, as well as to allow
switching between the display panels of different features.
** Highlights: This enables both modularised and efficient integration of features into
UI and allowed easy switching between different feature panels through the use of
Universal Commands.
** https://github.com/CS2103-AY1819S1-W10-4/main/pull/65[PR#65]

* *Other contributions*:

** Enhancements to new features:
*** Wrote additional tests for Meal Planner component to increase coverage.
** Community:
*** PRs reviewed (mostly wth regards to UI component):
https://github.com/CS2103-AY1819S1-W10-4/main/pull/83[#83],
https://github.com/CS2103-AY1819S1-W10-4/main/pull/84[#84],
https://github.com/CS2103-AY1819S1-W10-4/main/pull/56[#56]
*** Reported bugs and suggestions for other teams in the class (examples:
https://github.com/CS2103-AY1819S1-W13-1/main/issues/137[1],
https://github.com/CS2103-AY1819S1-W13-1/main/issues/136[2],
https://github.com/CS2103-AY1819S1-W13-1/main/issues/131[3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

=== Explanation of Meal Planner commands

include::../UserGuide.adoc[tag=mealplanner]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

---

=== Explanation of Meal Planner implementation

include::../DeveloperGuide.adoc[tag=mealplannerimplementation]

---

=== Meal Planner User Stories

include::../DeveloperGuide.adoc[tag=mealplanner]

---

=== Explanation of the modularisation of the UI component

include::../DeveloperGuide.adoc[tag=uimodularisation]

