= Chester Sng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLInic

---

== 1. Overview

This project portfolio serves to document my contributions to CLInic, a CS2103T (Introduction to Software Engineering) project, as part of my Computer Science curriculum in NUS.

CLInic is a desktop application made for clinics. The CLI in CLInic stands for Command Line Interface, which is the main method to use this application. CLInic also has a Graphical User Interface (GUI) to display information in a structured and user-friendly manner. This application uses Java as the primary programming language and uses JavaFX, HTML and CSS for the GUI.

The project scope for CLInic is to morph the given `addressbook-level4` into a clinic management application that allows users to manage patient and medicine information and additionally manage the clinic queue.

My task in CLInic is to implement a *Patient Queue Management System*, as well as to integrate the changes of my team to ensure CLInic works after every enhancement or change.

== 2. Summary of Contributions

* *Major enhancement*: Implementation of *Patient Queue Management System (PQMS)*
** What it does: This system allows the clinic to keep track of the queue in the clinic.
** Justification: This system improves the product significantly because it has created another use case for this application apart from just storing patient and medicine information.
** Highlights: This system builds upon patient information and medicine information. It models the real life queue system in the clinic and the 10 commands are made to be as intuitive as possible.

* *Minor enhancement*:
** Integration of `Patient` and `Document` class with PQMS through `DocumentAddCommand` and `DocumentDisplayCommand`
** Integration of `Patient` and `Medicine` class through `DispenseMedicineCommand`

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=chestersng[Functional code & Test Code]]

* *Other contributions*:

** Project management:
*** Took on the role of *Team Lead*
*** Managed releases `v1.1` - `v1.4` (4 releases) on GitHub
** Enhancements to test coverage:
*** Wrote tests for PQMS features to increase coverage from 67% to 75% (Pull request https://goo.gl/vQbh82[#109])
** Design:
*** Designed the mock-up of the https://cs2103-ay1819s1-w16-4.github.io/main/images/Ui.png[UI]
** Community:
*** Reviewed PRs (with non-trivial review comments): https://github.com/CS2103-AY1819S1-W16-4/main/pull/176[#176]
*** Fixed bugs for my teammates: https://github.com/CS2103-AY1819S1-W16-4/main/pull/180[#180]
*** Reported bugs and provided suggestions for other teams in the class (examples:  https://github.com/CS2103-AY1819S1-F11-3/main/issues/193[1], https://github.com/CS2103-AY1819S1-F11-3/main/issues/176[2], https://github.com/CS2103-AY1819S1-F11-3/main/issues/180[3])

== 3. Contributions to the User Guide


|===
|_Given below are part of the sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users. My full contribution can be viewed here: https://cs2103-ay1819s1-w16-4.github.io/main/UserGuide.html#pqms[PQMS Section 3.3]_
|===

include::../UserGuide.adoc[tag=pqms]
include::../UserGuide.adoc[tag=pqms2]

== 4. Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=pqms]
