= Ong Kai Le - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Piconso

---

== Overview

Piconso is an CLI (Command Line Interface) Image Editor designed and developed for quick and efficient image-editing. Many image-editors are complex and difficult to pick up, having a steep learning curve and sometimes even a steep price!

Unlike them, Piconso offers the same features, in a much more simplified manner. With Piconso, all traditional image-editing features can be performed solely through text commands, removing the hassle of working with a mouse. The interface can be used by photographers, designers, developers and more, and is very easy to pick up.


== Summary of contributions

* *Major enhancement*: Added *connectivity to Google Photos*
** What it does: Allows the user to login to Google Photos, and view, upload and download images on/to Google Photos.
** Justification: This feature improves the product significantly because it provides a user cloud connectivity to Google Photos, thus the user can immediately retrieve and work on a batch of images from the cloud, and upload his completed work there as well for easy storage and sharing.
** Highlights: This enhancement uses memoization ensure undo/redo commands are almost instant. Since transformations to images take significant time (especially large images) and that users typically want to quickly inspect the before and after of their transformation, it is necessary  for undo and redo to be fast. As such, after each transformation, the resulting transformed image is cached into a temporary folder. Undo and redo operations will shift a pointer leftwards or rightwards and read the selected image, instead of reapplying or reversing a transformation process which is time consuming.
** Credit: Google Photos Java Client API and Google OAuth API have been used throughout Google related commands.The feature that allows login to Google Photos was also based upon the [https://github.com/google/java-photoslibrary/blob/master/sample/src/main/java/com/google/photos/library/sample/demos/AlbumDemo.java [example found here]]
* *Minor enhancement*: Added a ls command that allows the user to list the files in their current directory. Additionally, also created and linked the UIs for FilmReel (shows images in current directory batch) and HistoryList (shows history of transformations performed on image)

//* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_
* *Code contributed*: [https://github.com/CS2103-AY1819S1-T09-3/main/commits?author=chivent[All commits]] [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=chivent[Project Code Dashboard]]


* *Other contributions*:

** Project management:
*** Help manage tagging of milestone code (v1.1-v1.2)
*** Participated in creating and tagging issues, and merging/reviewing PRs
** Enhancements to existing features:
*** Updated the status footer bar UI to display current directory and google connectivity status (Pull requests https://github.com/CS2103-AY1819S1-T09-3/main/pull/80[#80])
** Documentation:
*** Added detailed implementation documentation for the google login feature in Developer Guide, including diagrams: https://github.com/CS2103-AY1819S1-T09-3/main/pull/131[#131]
*** Updated the User Guide for the google features: https://github.com/CS2103-AY1819S1-T09-3/main/pull/103[#103], https://github.com/CS2103-AY1819S1-T09-3/main/pull/131[#131]
** Community:
*** PRs reviewed: https://github.com/CS2103-AY1819S1-T09-3/main/pull/44[#44], https://github.com/CS2103-AY1819S1-T09-3/main/pull/37[#37]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=google]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

[NOTE] This section is still in progress, features for Google Ls, Upload and Download are yet to be fully completed.
include::../DeveloperGuide.adoc[tag=google]
