= Chai Jie Feng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: EventsPlus+

---

== Overview

EventsPlus+ is a desktop address book application catered for busy university students to
manage their contacts, events, project meetings and ad-hoc events efficiently.
EventsPlus+ aims to simplify some of the more time-consuming administrative tasks
such as coordinating location and date of ad-hoc events using a Command Line Interface (CLI)
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *import contacts function*
** What it does: Allows the user to import contacts from external source (link:https://contacts.google.com/[google contacts]) into EventsPlus+.
** Justification: Users should be able to easily import contacts from external source without having to go through the trouble of adding in 
contacts 1 by 1.
** Highlights: Users will be notified with the number of successful imported contacts. Failure of importing should be the caused by 
bad formatting or missing mandatory fields. 

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=cjiefeng[Functional code & Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` on GitHub

** Documentation:
*** Updated documentation for the enhancements as above: (Pull requests  https://github.com/CS2103-AY1819S1-W13-2/main/pull/101[#101],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/185[#185],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/187[#187])
*** Updated User Guide with initial planned features (Pull requests https://github.com/CS2103-AY1819S1-W13-2/main/pull/4[#4])
*** Updated author name for reposense (Pull requests https://github.com/CS2103-AY1819S1-W13-2/main/pull/123[#123])

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S1-W13-2/main/pull/5[#5], 
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/9[#9], 
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/130[#130], 
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/172[#172]
*** Reported bugs and suggestions for other teams in the class (examples: https://github.com/CS2103-AY1819S1-W12-4/main/issues/124[1],
  https://github.com/CS2103-AY1819S1-W12-4/main/issues/115[2],
  https://github.com/CS2103-AY1819S1-W12-4/main/issues/114[3])


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
include::../UserGuide.adoc[tag=importContacts]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../DeveloperGuide.adoc[tag=importContacts]
