= Clinton Law - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLInic

---

== Introduction

This Project Portfolio Page documents `clawyq`'s contributions to the development of CLInic.

CLInic is a desktop application made to manage and expedite operations in clinics. It was inspired by
the Command Line Interface (CLI), which allowed users to issue commands to the computer efficently.
However, the CLI's non-visual display and walls of cryptic text makes it intimidating to the general,
non-tech-savvy populous.

These reasons were the main impetus behind CLInic, which marries the **simplistic design** and
**efficient command issuing mechanism** of the CLI with an intuitive Graphical User Interface (GUI).
This culminated in a clean application that is easy for anyone to use, all while providing the powerful
 functionalities and efficiencies provided by a CLI.

Below are some of the key functionalities provided by CLInic:

* Allows users to manage patient and medicine information
* Allows users to easily generate documents to be issued by a clinic like `Medical Certificates`,
`Receipts` and `Referral Letters` efficiently
* Provides intuitive workarounds to normally arduous but common administrative tasks such as restocking
and dispensing medicine

CLInic is the product of semester-long efforts of a team of five students from NUS School Of
Computing as part of the CS2103T Software Engineering module. Through the course of the module, the
team morphed a very primitive application, which had basic add/delete functionalities akin to that of a
 phone/contact book, into a fully-fledged clinic management application. The main features of the
 application is primarily coded in Java while the GUI is handled by JavaFX, HTML and CSS.

I played a major role in the development of the Document class, the relevant Receipt, MedicalCertificate
and Referral classes that extend it and the relevant patient management operations that are required for
them to work.

== Summary of contributions

* *Major enhancement*: Implementation of the `*Document*` class, its accompanying HTML template and
extending classes, which include `Receipt`, `MedicalCertificate` and `ReferralLetter`.
** What it does: It takes in the information of a document that is to be printed by the clinic and
generates a `HTML` file for it.
** Justification: This functionality improves the application as it simplifies the generation of documents
that are required by the clinic. This makes the administrative tasks in the clinic easier and faster,
allowing for a boost in productivity for the users of the application, which translates into shorter wait
times at the clinic for the patients.
** Highlights: This functionality allows for seamless transfer of information from doctors to receptionists
of the clinic during consultation, which when coupled with the fast retrieval of information from the
application's database of `Patient` and `Medicine` information, makes for efficient generation of relevant
documents.

* *Minor enhancements*:
** Improved and helped with the implementation of `ServedPatient` and `ServedPatientListManager`, which are intermediate
abstractions that helped 'finalise' the information to be used for the generation of `Document`.
** Integrated `MedicalCertificate` with the `DocumentAddContentCommand`
** Implemented the `HTML` template which all the classes that extend `Document` use to format their own information

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Enhancements to features:
*** Wrote tests for various features to increase coverage from 59% to 63% (Pull requests: https://github.com/CS2103-AY1819S1-W16-4/main/pull/97[#97],
https://github.com/CS2103-AY1819S1-W16-4/main/pull/98[#98],
https://github.com/CS2103-AY1819S1-W16-4/main/pull/104[#104])
** Community:
*** Reviewed PRs and provided constructive feedback: (Pull requests: https://github.com/CS2103-AY1819S1-W16-4/main/commit/f8b4ae0b80adfaa3355d82c396a3017d8b6f4b26[#110],
https://github.com/CS2103-AY1819S1-W16-4/main/commit/6c731cdce1270a4009cad3f4e65a5b7b98030f67[#119],
https://github.com/CS2103-AY1819S1-W16-4/main/commit/3740d6e8b3a2b90126fcab6fdd250817bd8981aa[#120])


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=document]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=document]
