= Clinton Law - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLInic

---

== Introduction

This Project Portfolio Page documents my contributions to the development of `CLInic`, the product of a team of five
students from NUS School Of Computing as part of the `CS2103T Software Engineering` module. The main
features of the application are coded in `Java` while the GUI is handled by `JavaFX`, `HTML` and `CSS`.

`CLInic` is a desktop application made to manage and expedite operations in clinics. The efficiency of typing commands
yet cryptic walls of intimidating text of the CLI were the main impetus behind `CLInic`. `CLInic` marries the
**simplistic design** and **efficient command issuing mechanism** of the CLI with an **intuitive** Graphical User
Interface (GUI). This culminated in an application that is easy for **anyone** to use, all while providing the powerful
 functionalities and efficiencies offered by a CLI. Below are some of the key features provided by `CLInic`:

* Allows users to manage patient and medicine information
* Allows users to easily generate documents to be issued by a clinic like `Medical Certificates` efficiently
* Provides intuitive workarounds to normally arduous but common administrative tasks such as restocking
and dispensing medicine

I played a major role in the development of the `Document` class, the relevant `Receipt`, `MedicalCertificate`
and `ReferralLetter` classes that extend it and the relevant patient management operations that are required for
them to work.

== Summary of contributions

* *Major enhancement*: Implemented the `Document` class, its accompanying HTML template and
extending classes, which includes the `Receipt`, `MedicalCertificate` and `ReferralLetter` classes.
** What it does: It takes in the information of a document that is to be printed by the clinic and
generates a `HTML` file for it.
** Justification: This functionality simplifies the generation of documents that are required by the clinic.
This makes the administrative tasks in the clinic easier and faster, *boosting the productivity of its users*,
 translating into *shorter wait times at the clinic for the patients*.
** Highlights: This functionality allows for *seamless transfer of information from doctors to receptionists*
of the clinic during consultation, which when coupled with the fast retrieval of information from the
application's database of `Patient` and `Medicine` information, makes for *efficient generation of relevant
documents*.

* *Minor enhancements*:
** Improved and helped with the implementation of `ServedPatient` and `ServedPatientListManager`, which are intermediate
abstractions(placeholders) that help to 'finalise' the information to be used for the generation of `Document`.
** Integrated `MedicalCertificate` with the `DocumentAddContentCommand`.
** Designed the `HTML` template which all the classes that extend `Document` use to format their information.

* *Code contributed*: https://github.com/CS2103-AY1819S1-W16-4/main/tree/master/src/main/java/seedu/address/model/document[Implementation of Document and its relevant classes], and their https://github.com/CS2103-AY1819S1-W16-4/main/tree/master/src/test/java/seedu/address/logic[associated test codes.]

* *Other contributions*:

** Enhancements to features:
*** Wrote tests for various features to increase coverage from 59% to 63% (Pull requests: https://github.com/CS2103-AY1819S1-W16-4/main/pull/97[#97],
https://github.com/CS2103-AY1819S1-W16-4/main/pull/98[#98],
https://github.com/CS2103-AY1819S1-W16-4/main/pull/104[#104])
** Community:
*** Reviewed PRs and provided constructive feedback: (Pull requests: https://github.com/CS2103-AY1819S1-W16-4/main/pull/110[#110],
https://github.com/clawyq/main/pull/6[#119],
https://github.com/CS2103-AY1819S1-W16-4/main/pull/120[#120])
** Documentation:
*** Wrote the introduction to the User Guide (Pull Request: https://github.com/CS2103-AY1819S1-W16-4/main/pull/134[#134])
*** Added many examples in the User Guide to demonstrate how various commands work. (Pull Request: https://github.com/CS2103-AY1819S1-W16-4/main/pull/138[#138])
*** Standardised the formatting of the User Guide and corrected any incorrect use of language. (Pull Requests: https://github.com/CS2103-AY1819S1-W16-4/main/pull/139[#139],
 https://github.com/CS2103-AY1819S1-W16-4/main/pull/172[#172],
 https://github.com/CS2103-AY1819S1-W16-4/main/pull/174[#174])

== Contributions to the User Guide

|===
|_Given below are the sections I have contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

[.big.underline]#*Implementation of the Patient Record Management System*#

include::../UserGuide.adoc[tag=patientfirsthalf]

== Contributions to the Developer Guide

|===
|_Given below are the sections I have contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

[.big.underline]#*Implementation of the Document class*#

include::../DeveloperGuide.adoc[tag=documentpreamble]

[.big.underline]#*Implementation of the Receipt class*#

include::../DeveloperGuide.adoc[tag=receipt]
