= Ang Chen Shin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:sectnums:
:stylesDir: ../stylesheets

PROJECT: Student Schedule Planner

---

== Overview

This portfolio showcases the software engineering skills I acquired during my time of study in National University of
 Singapore.

Student Schedule Planner (SSP) is a desktop application created by my team T12-3 for CS2103T module. SSP
aimed to help university students to manage their tasks effectively. It is morphed from an existing product called
AddressBook, with constraints such as the primary mode of user input must be via command-line interface.

My contributions to the project included adding `firstday`, `listday` and `listweek` commands to aid the
users in better monitoring of their tasks.

== Summary of Contributions

* *Major enhancement*: Added *task monitoring system*
** What it does: This feature allows user to know what is the current academic week whenever they launch the
application within the academic semester. It also allow users to know what tasks they have that are due on the current
date or from the current date until the closest Sunday.
** Justification: This feature allows user to monitor their tasks easier as they may know that they have certain tasks
 due on a particular week and could use this to plan their remaining time properly. Users could also easily know what
  tasks they have on the current week.
** Highlights: This implementation was challenging as it required creating a new `model` and `storage` for saving and
retrieving the academic weeks data.
** Credits: https://stackoverflow.com/questions/1816673/how-do-i-check-if-a-file-exists-in-java[#1],
https://stackoverflow.com/questions/156503/how-do-you-assert-that-a-certain-exception-is-thrown-in-junit-4-tests[#2],
https://stackoverflow.com/questions/5175728/how-to-get-the-current-date-time-in-java[#3],
https://stackoverflow.com/questions/428918/how-can-i-increment-a-date-by-one-day-in-java[#4],
https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html[#5]

* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=crimsonang[Project
Code Dashboard]

* *Other contributions*:

** Project management:
*** Managed releases `mid-v1.3` - `v1.3` (2 releases) on GitHub
** Documentation:
*** Morphed existing diagrams of the Developer Guide:
https://github.com/CS2103-AY1819S1-T12-3/main/pull/81[#81]
*** Updated `Target User Profile` of the Developer Guide:
https://github.com/CS2103-AY1819S1-T12-3/main/pull/1[#1]
*** Added `User Stories` of the Developer Guide:
https://github.com/CS2103-AY1819S1-T12-3/main/pull/1[#1]

** Community:
*** Contributed to forum discussions: https://github.com/nus-cs2103-AY1819S1/forum/issues/132[#132],
https://github.com/nus-cs2103-AY1819S1/forum/issues/146[#146]
*** Some parts of `listweek` command I added was adopted by a classmate:
https://github.com/CS2103-AY1819S1-T12-3/main/pull/125[#125]
*** Some parts of `listday` command test cases I added was adopted by a classmate:
https://github.com/CS2103-AY1819S1-T12-3/main/pull/201[#201]
** Tools:
*** Integrated two Github plugin (AppVeyor, Coveralls) to the team repo

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide to aid the user in using the application._
|===

include::../UserGuide.adoc[tag=firstday]

include::../UserGuide.adoc[tag=listday]

include::../UserGuide.adoc[tag=listweek]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide that includes my technical documentation and depth to
 aid developer to understand how the application functions._
|===

include::../DeveloperGuide.adoc[tag=generateacademiccalendar]

include::../DeveloperGuide.adoc[tag=viewarangeoftasks]

include::../DeveloperGuide.adoc[tag=viewarangeoftasks2]
