= Ang Chen Shin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Student Schedule Planner

---

== Overview

Student Schedule Planner (SSP) is a desktop application aimed to help students to manage their tasks effectively. The
user interacts with SSP using a Command-Line Interface (CLI), and it has a Graphical User Interface (GUI)
created with JavaFX.

== Summary of contributions

* *Major enhancement*: added *command to generate academic calendar weeks*
** What it does: This feature allow user to use a command to generate the entire academic calendar weeks based on the
 first day of the academic semester. Whenever the user launches the application within the academic semester, that
 particular week's description will be appended to the application title so the user know which academic week that
 particular week is.
** Justification: This feature allows user to monitor their tasks easier as they may know that they have certain task
 due on a particular week and could use this to gauge the number of weeks they have left for the task.
** Highlights: This implementation was challenging as it required creating a new model and storage for saving and
retrieving the academic week data.
** Credits: https://stackoverflow.com/questions/1816673/how-do-i-check-if-a-file-exists-in-java

* *Minor enhancement*:
** added a "list day" command to display the tasks from current date.
** added a "list week" command to display the tasks from current date till the closest Sunday.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `mid-v1.3` - `v1.3` (2 releases) on GitHub
** Documentation:

*** Updated Target User Profile of the Developer Guide (Pull requests
https://github.com/CS2103-AY1819S1-T12-3/main/pull/1[#1])
*** Added User Stories of the Developer Guide (Pull requests
https://github.com/CS2103-AY1819S1-T12-3/main/pull/1[#1])

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (example:  https://github.com/nus-cs2103-AY1819S1/forum/issues/132[1])
*** Some parts of the listweek feature I added was adopted by a classmate
(Pull Request https://github.com/CS2103-AY1819S1-T12-3/main/pull/125[125])
** Tools:
*** Integrated two Github plugin (AppVeyor, Coveralls) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=listday]

include::../UserGuide.adoc[tag=listweek]

include::../UserGuide.adoc[tag=firstday]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=viewarangeoftasks]

include::../DeveloperGuide.adoc[tag=generateacademiccalendar]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
