= Lin Deming - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ModsUni

---

== Overview

modsUni is a desktop timetable management application created by students for students. It incorporates a simple GUI with majority of its user interactions occurring in its in-built CLI.

== Summary of contributions

* *Major enhancement*: **The ability to add/remove/edit modules** was added.
** What it does: It allows administrators to make changes to any module in the database.
** Justification: This feature allows administrators to keep the module database up to date so that students can continue to generate schedules that are valid.

* *Minor enhancement*: The show user command was added that show the list of usernames to facilitate user account management.

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=admincommands]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=moduledatabaseadministration]

