= TRAVIS CHING JIA YEA - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Hallper

---

== 1. Introduction

This portfolio documents my role and contributions to the project, Hallper. This project was undertaken as part of a
requirement for the module CS2103T - Software Engineering, offered in the National University of Singapore (NUS). The main goal of the project is to enhance and add value to the application, AddressBook Level 4.

*About Hallper:* Hallper is a desktop application providing administrative convenience. It is catered to the Junior Common Room Committee (JCRC)
of the halls of NUS, whose main responsibility is to organise and manage all student related activities in hall and look after the welfare of hall residents.
Users interacts with Hallper using a Command Line Interface (CLI), whilst a Graphic User Interface (GUI) implemented with JavaFX displays the relevant information to the user. Hallper is written
in Java and contains approximately 60k lines of code (LoC). Integrated within Hallper is a range of features such as calendar, email and budgeting. Besides that, features such as erase, search and clear from the existing AddressBook Level 4 application
have been enhanced.

*My role and contributions:* My contribution to the project is the implementation the calendar feature and all its relevant commands. The commands that facilitate the calendar feature includes creating calendars, adding events, deleting events and viewing calendars.
My role in this project is to make sure that the milestones we set collectively as a team are met on time. This includes reviewing the codes of my team members and doing acceptance testing (making sure the feature solves the problem it claims to solve).

== 2. Summary of contributions
This section lists the major and minor enhancements I have contributed to the project, Hallper as well as miscellaneous contributions in other aspects of the project.

I implemented the calendar feature with external libraries,  https://github.com/ical4j/ical4j[iCal4j] and http://jfxtras.org/[JFxtras].

* *Major enhancement 1*: added the ability to create calendars in Hallper
** What it does: This feature allows the user (JCRC member) to create monthly calendars in Hallper.
** Justification: This feature improves the product significantly because a JCRC member needs to keep track of the monthly events happening in hall, and a calendar is just the right tool. Being able to keep track of hall events in a calendar also allows the JCRC member to mitigate event date clashes with ease.
** Highlights: Calendars are created in the file format `.ics`. This file format is chosen because it is compliant with the RFC 5545 format, which is recognised in the industry. Albeit the implementation of this feature requires an in-depth understanding of the external library https://github.com/ical4j/ical4j[iCal4j]. This is not an issue as the library is widely used and well documented, new developers can easily pick up and extend the current features.

* *Major enhancement 2*: added the ability to view calendars in Hallper
** What it does: This feature allows the user (JCRC member) to view monthly calendars in Hallper by displaying the calendar on the GUI.
** Justification: This feature improves the user experience as the user can observe changes made on the calendar dynamically. Besides that, the calendar is displayed alongside the command line interface (CLI), eliminating the need to switch between windows. In other words, the user can create, modify and view calendars in Hallper just by typing the keyboard.
** Highlights: The implementation of this feature requires an in-depth understanding of Java FXML API, JavaFX, XML, http://jfxtras.org/[JFxtras] and how they work together. It was challenging as it required changes to existing commands and interaction with the main window had to be correctly handled.

* *Minor enhancement*: added add event and delete event command that allows the user to modify calendar content.

* *Code contributed*:
[ https://github.com/CS2103-AY1819S1-W16-1/main/tree/master/src/main/java/seedu/address[Functional code] ]
[ https://github.com/CS2103-AY1819S1-W16-1/main/tree/master/src/test/java[Test code] ]
[ https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=gilga&sort=displayName&since=2018-09-12&until=2018-11-01&timeframe=day&reverse=false&repoSort=true[RepoSense] ]

* *Other contributions*:

** Enhancements to existing features:
*** Wrote tests for calendar features to increase coverage from 54% to 66% (Pull request: https://github.com/CS2103-AY1819S1-W16-1/main/pull/119[#119])

** Documentation:
*** Updated the README:
(Pull request: https://github.com/CS2103-AY1819S1-W16-1/main/pull/22[#22])
*** Updated the Developer Guide:
(Pull request: https://github.com/CS2103-AY1819S1-W16-1/main/pull/73[#73],
 https://github.com/CS2103-AY1819S1-W16-1/main/pull/97[#97],
 https://github.com/CS2103-AY1819S1-W16-1/main/pull/174[#174])
*** Updated the User Guide:
(Pull request: https://github.com/CS2103-AY1819S1-W16-1/main/pull/120[#120],
 https://github.com/CS2103-AY1819S1-W16-1/main/pull/136[#136])

** Community:
*** Pull request reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S1-W16-1/main/pull/13[#13]
*** Reported bugs and suggestions for other teams in the class
(Issues: https://github.com/CS2103-AY1819S1-T16-4/main/issues/172[#172], https://github.com/CS2103-AY1819S1-T16-4/main/issues/173[#173], https://github.com/CS2103-AY1819S1-T16-4/main/issues/176[#176], https://github.com/CS2103-AY1819S1-T16-4/main/issues/179[#179])

** Tools:
*** Integrated Travis CI and auto publishing of documents to the project (Pull request: https://github.com/CS2103-AY1819S1-W16-1/main/pull/3[#3])
*** Integrated a third party library (iCal4j) to the project (Pull request: https://github.com/CS2103-AY1819S1-W16-1/main/pull/17[#17])
*** Integrated a third party library (JFxtras) to the project (Pull request: https://github.com/CS2103-AY1819S1-W16-1/main/pull/107[#107])

== 3. Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=calendar]


== 4. Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=calendar]

