= Sophia Simangan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ClinicIO

ClinicIO is a desktop clinic management application used for teaching Software Engineering principles. The user interacts with it using a CLI. It is written in Java, and has about 10 kLoC.

== Overview

This portfolio contains

== Summary of contributions

* *Major enhancement*: added *the ability to create/cancel appointments*
** What it does: This feature provides users the basic actions of managing appointments with ease.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future.

* *Minor enhancement*:

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:
https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=gingivitiss&sort=displayName&since=2018-09-30&until=2018-11-12&timeframe=day&reverse=false&repoSort=true

** Documentation:
*** Added command information regarding the appointment feature into the User Guide: https://github.com/CS2103-AY1819S1-W14-1/main/pull/119

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=appointmentcommands]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=apptfeature]


