= He Xinyi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: iScheduler Xs Max

---

== Overview

iScheduler Xs Max is a desktop scheduler application morphed from the original Address Book sample application (Level 4). As its name suggests, it is used for scheduling events. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 20 kLoC.

== Summary of contributions

* *Major enhancement*: added *Reminder Feature of the scheduler*
** What it does: allows the users to create events with multiple reminders for an event. The feature is integrated with all iScheduler commands.
** Justification: This feature improves the product significantly because users will want to be reminded of important events.
** Highlights: This enhancement affects all existing commands and requires updates in `Logic`, `UI`, `Model` and `Storage`. The implementation too was challenging as it required research on
multi-thread programming as the app has to continuously checking what reminders to pop up.

* *Minor enhancement*: added more customised commands for users: `addReminder`, `deleteReminder`, `postponeReminders`
that allow the users to more easily use Reminder Feature as compared to `add` and `edit` command.

* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=hexinyiyi[Project Code Dashboard]

* *Other contributions*:

** Project management:
*** Managed team repository's pull requests. Helped teammates debug.
** Documentation:
*** Update documentation for Reminder Feature. Enhanced documentations for `add`, `edit` commands in the User Guide (Pull requests https://github.com/CS2103-AY1819S1-F11-1/main/pull/121[#121], https://github.com/CS2103-AY1819S1-F11-1/main/pull/258[#258], https://github.com/CS2103-AY1819S1-F11-1/main/pull/291[#291])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

3.9. Reminder Operations
include::../UserGuide.adoc[tag=Reminder Feature]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

3.9. Reminder Operations
include::../DeveloperGuide.adoc[tag=Reminder Feature]
