= Neo Kai Jun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Overview
This portfolio summarizes my contributions towards the project I have undertaken in the course **CS2103T - Software
Engineering**. It aims to demonstrate the theoretical and practical knowledge I have gained in the field of Software
Engineering over the semester.

== PROJECT: MeNUS
*MeNUS* is an integrated restaurant management system designed for restaurant owners. It comprises five sub-management
 systems - 1)Menu, 2)Inventory, 3)Sales, 4)Reservation and 5)Authentication, each of which plays an indispensable
 role in ensuring the success of a restaurant business. They were meticulously developed to streamline the process of
  tracking dishes, ingredients, bookings and financial records while upholding a substantial level of security.

*MeNUS* provides a Command Line Interface (CLI) for restaurant owners to interact with and is complemented with a
Graphical User Interface (GUI) that is constructed with https://docs.oracle.com/javafx/2/overview/jfxpub-overview.htm[JavaFX].
MeNUS is written in https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html[Java 9]
with approximately 25 kLOC.


== Summary of contributions
* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=hyperionnkj[RepoSense]
* *Major enhancement*: added Sales Management features to help restaurant owners keep track of financial records.
** What it does: allows the user to record, edit and delete financial records. Besides, they can view the sales
report of a specified date, and even the revenue ranking of the items and dates. An auto-ingredient update mechanism
was also incorporated in command to record sales, so restaurant managers would no longer have to manually update them
 every day.
** Justification: These features help ease the difficulty in keeping track of financial records every day. It also
helps restaurant managers make strategic financial and marketing decisions to expand their business in the long run.
** Highlights: This enhancement adds on to the limited number of commands available in MeNUS. It requires an in-depth
analysis of design alternatives as well as understanding how the entire code base interacts with one another. The
implementation too was challenging as the auto-ingredient update mechanism requires knowledge of how menus and
ingredients management works.

* *Other contributions*:

** Project Management:
*** Manage the integration aspect of the MeNUS. Ensure interaction between various components of the app goes smoothly
as intended.

** Community:
*** PRs reviewed (with non-trivial review comments)
*** Reported bugs and suggestions for other teams in the class

** Quality Assurance:
*** Written all the test cases related to Sales management which include unit testing, system testing and integration
 testing. This helps improve the overall coverage of the app beyond 90%.

** Documentation:
*** Written the Sales command descriptions in User guide
*** Written and updated use cases, user stories in Developer guide.
*** Written the implementation details of display-sales and auto-ingredient update features.
*** Drawn UML model to ease understanding and complement written explanation
*** Made general enhancements to the User Guide and Developer Guide

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

//include::../DeveloperGuide.adoc[tag=undoredo]
