= He Zhenfeng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ModsUni

---

== Overview

https://github.com/hzf1174/main[*modsUni*] is a desktop timetable management application targeted at
student at National University of Singapore(NUS). It aims to make the module planning process easier and
more visual. It provides all users with the ability to make class schedules within a private secure account. +
https://github.com/hzf1174/main[*modsUni*] incorporates a simple display, technically called Graphical User Interface(GUI),
with majority of its user interactions occurring in its in-built Command Line Interface(CLI), which is suitable for
users who prefer typing instead of clicking mouse.


== Summary of contributions

* *Major enhancement*: added *User Module Management* feature
** What it does: Allows users to add and remove modules in their module lists, and search modules in the database.
** Justification: This feature provides users basic actions to plan for their candidature and it is also one of the foundational
features of modsUni.


* *Minor enhancement*: display module and module list
** What it does: Allows users to figure out the details of every module, and makes the module list visually.
** Justification: This feature provides users better module planning experience as visualization provides users overall grasp.

* *Code contributed*:

* *Other contributions*:


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]

