= Ivan Ho - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Piconso

---

== Overview

Piconso is an CLI (Command Line Interface) Image Editor designed and developed for quick and efficient image-editing. Many image-editors are complex and difficult to pick up, having a steep learning curve and sometimes even a steep price!

Unlike them, Piconso offers the same features, in a much more simplified manner. With Piconso, all traditional image-editing features can be performed solely through text commands, removing the hassle of working with a mouse. The interface can be used by photographers, designers, developers and more, and is very easy to pick up.


== Summary of contributions

* *Major enhancement*: added *the ability to undo/redo previous transformations*
** What it does: allows the user to undo all previous transformations one at a time. Preceding undo transformations can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in transformations and the app should provide a convenient way to rectify them.
** Highlights: This enhancement uses memoization ensure undo/redo commands are almost instant. Since transformations to images take significant time (especially large images) and that users typically want to quickly inspect the before and after of their transformation, it is necessary  for undo and redo to be fast. As such, after each transformation, the resulting transformed image is cached into a temporary folder. Undo and redo operations will shift a pointer leftwards or rightwards and read the selected image, instead of reapplying or reversing a transformation process which is time consuming.

// * *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

//* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_
* *Code contributed*: [https://github.com/CS2103-AY1819S1-T09-3/main/commits?author=ihwk1996[All commits]] [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=ihwk1996[Project Code Dashboard]]


* *Other contributions*:

** Project management:
*** Set up team organization and repository on GitHub
** Enhancements to existing features:
*** Wrote tests for undo/redo feature including various test utility classes for team to use for testing (Pull requests https://github.com/CS2103-AY1819S1-T09-3/main/pull/105[#105], https://github.com/CS2103-AY1819S1-T09-3/main/pull/110[#110])
** Documentation:
*** Added detailed implementation documentation for the undo/redo feature in Developer Guide, including diagrams: https://github.com/CS2103-AY1819S1-T09-3/main/pull/56[#56], https://github.com/CS2103-AY1819S1-T09-3/main/pull/60[#60]
** Community:
*** PRs reviewed: https://github.com/CS2103-AY1819S1-T09-3/main/pull/37[#37], https://github.com/CS2103-AY1819S1-T09-3/main/pull/55[#55], https://github.com/CS2103-AY1819S1-T09-3/main/pull/57[#57], https://github.com/CS2103-AY1819S1-T09-3/main/pull/61[#61]
** Tools:
*** Set up Travis(Continuous Integration) to perform automated testing of test cases and auto-publishing of documentation

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users. (Since undo/redo are simple to understand, there is not much to document here. More details are in the implementation of undo/redo in the Developer Guide)_
|===

include::../UserGuide.adoc[tag=undoredo]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]
