= Amabel Yeo - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoURL: https://github.com/CS2103-AY1819S1-W16-2/main/pull

== PROJECT: SocialCare

:sectnums:
== Overview

This portfolio page documents my involvement in SocialCare, a project done as part of the CS21303T Software Engineering module taught in NUS.
For this project, my team had the goal to _'harness the potential of software to create sustainable social change'_.

With our goal in mind, we developed SocialCare, a desktop application made for social welfare organizations.
This application is designed to help manage volunteers and events effectively. This is done through the Command Line Interface (CLI), which help users to interact with the application; and the Graphical User Interface (GUI), which displays information in a user-friendly manner.

My main role as a developer for SocialCare was to implement *record management functions*, which enable users to do the following:

* View volunteers assigned to an event
* Assign volunteers to an event
* Update volunteering records for volunteers
* Delete volunteering records of volunteers

== Summary of Contributions
* *Major enhancement*:
Added commands to *manage volunteer records*
** What it does:
The commands implemented allow users to manage volunteering records.
They will be able to assign volunteers to events and update the number of hours contributed by the volunteer.

** Justification:
These functions are part of the core requirements for the application because we want users to be able to effectively manage volunteering records.

** Highlights:
This enhancement is completely new and required an in-depth analysis of design alternatives.
It was challenging as to properly implement this, a complete understanding of all code components was needed.

* *Minor enhancement*:
** Added a command to allow users to *switch between panels*.
** Created charts for the `overview` command.

* *Code contributed*:
Here is a https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=imarbles[link]
to my code on the Project Code Dashboard.


* *Other contributions*:

** Project management:
*** Set up the team repository on GitHub

*** Ensured that project deliverables were done on time and in the right format
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: link:{repoURL}/76/[#76], link:{repoURL}/129/[#129]
*** Rewrote the quick start section of the User Guide: link:{repoURL}/154/[#154]
*** Revised content for the Logic component in the Developer Guide: link:{repoURL}/93/[#93]
** Community:
*** Reviewed PRs for team members (with non-trivial review comments): link:{repoURL}/58/[#58], link:{repoURL}/109/[#109], link:{repoURL}/114/[#114]
** Tools:
*** Integrated Travis to the Github repository

== Contributions to the User Guide


|===
| Below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=command-record]
include::../UserGuide.adoc[tag=command-switch]


== Contributions to the Developer Guide

|===
| Below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=command-manage]
include::../DeveloperGuide.adoc[tag=command-switch]


