= JAVEN SEOW YU BIN - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Hallper

== Overview

This Project Portfolio Page aims to illustrate what I have learnt while working on Hallper, as well as to document my
contributions to the project. The different sections below will specify my contributions to different aspects of the
project.

Hallper is a desktop application that is a centralized management system which is catered for the use by the Junior
Common Room Committee (JCRC) of the halls in any school. Most of my team mates have stayed or are still staying in a hall
and we identified that the JCRC in our respective halls seem to be having a hard time dealing with their administrative
duties as there they have to liaise with many different parties. As a result, my team decided to build a centralized
management system as our project for our software engineering module so as to help alleviate the inconvenience that
they encounter while executing their duties. Hallper is an easy to use application which brings about much convenience to
the JCRC since not much mouse interaction is required from them as everything can be done just by typing the commands
available. By consolidating the types of features needed all into a single application, this will save the JCRC the
trouble of having to open many different applications on their computer.

The main features included in Hallper are email writing, budget management, calendar creation, profile picture
uploading as well as import and export of Hallper. With all these features in place, we believe that Hallper will be the
one-stop solution for all JCRCs.

== Summary of contributions

* *Major enhancement 1*: added a *image function to upload profile pictures into Hallper*
** What it does: This feature allows the user to upload profile pictures for residents that the user specifies.
** Justification: This feature adds value to the product as the JCRC will then be able to see the faces of each resident
through Hallper.
** Highlights: This feature required the HTML file that is used to display the profile to receive relevant information,
along with the tagged profile picture of the specified resident.

* *Major enhancement 2*: added a *search function to search for residents by room number, school or CCA*
** What it does: This feature allows the user to search for residents based on room numbers, schools or even the CCAs that the residents are in.
** Justification: This feature improves the product significantly because a user might want to find residents based on certain specifications.
** Highlights: This enhancement required manipulation of existing data fields of the residents since multiple specifications can be used as a search criteria

* *Minor enhancement*: updated the data fields that were required for each resident.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed release `v1.3` on GitHub
** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Reorganized the User Guide to make it more user-friendly: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
** Tools:
*** Integrated a third party library (Apache Commons IO) to the project (https://github.com[#42])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=search]


include::../UserGuide.adoc[tag=image]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=image]


== PROJECT: PowerPointLabs

---

