= Jeremy Yew - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CAPTracker

---

== Overview

CapTracker is a desktop application. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Transcript file storage feature.
** What it does: Automatically saves and updates all of user's transcript data into a file, and loads this file. File path for transcript data file can be changed in preferences file. 
** Justification: Users should be able to access previously created modules when opening the app again, otherwise they would have to re-enter all their modules again. They can also load their data in another computer or share it with other users if desired, simply by sharing the file itself. 
** Highlights: 
*** Transcript data file is updated whenever the in-memory Transcript object is changed. 
*** By using the `Jackson` library to store the Transcript data as a JSON file instead of an XML file, we avoid having to write `XMLSerializableTranscript` and `XMLAdaptedModule` classes. Instead, we simply register a custom `JSONTranscriptDeserializer` on the `ReadOnlyTranscript` class so that when we read from the JSON file, Jackson's `ObjectMapper` is able to use the values to reconstruct the saved object. This reduces code complexity. 
*** `JSONTranscriptDeserializer` uses null-returning node access with `get` when a missing value signifies type-incorrectness and should raise an exception. It uses safe node access with `path` when the field may be missing but the object can be instantiated without it. 
** Credits: Relied on patterns in `Storage` classes in AB-4. 

* *Minor enhancement*: Display and updating of current CAP and CAP Goal.
** What it does: Displays current CAP, immediately updates whenever completed modules are edited. Displays CAP Goal if set, else displays NIL; immediately updates whenever incomplete modules are changed or adjusted. 
** Justification: Users should be able to view their current CAP and CAP Goal as they are updated, without having to request for them through a command. This enables them to easily evaluate their current academic standing, and set new academic goals. 

* *Code contributed*:  https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=jeremy_yew

* *Other contributions*:
** Project management:
*** Guided planning of early project timeline and milestone setting. 
*** Managed release `v1.1` (1 release) on GitHub.
*** Maintained issue tracker and review/merger of pull requests.
** Enhancements to existing features:
*** Enabled app to load initial sample module data (link:https://github.com/CS2103-AY1819S1-T13-4/main/pull/27[#27]).
*** Coded initial GUI layout (link:https://github.com/CS2103-AY1819S1-T13-4/main/pull/52[#52]).
** Documentation:
*** Updated existing content of the Storage Section of Developer Guide. 
//*** Added Sequence Diagram of Current Cap and Cap Goal in Developer Guide. 
//*** Added Sequence Diagram of SaveTranscript and ReadTranscript in Developer Guide. 
*** Updated existing content of the "Saving your module data" section of User Guide, and helped refined other member's documentation of commands. 
** Community:
*** PRs reviewed (with non-trivial review comments): 
link:https://github.com/CS2103-AY1819S1-T13-4/main/pull/23[#23],
link:https://github.com/CS2103-AY1819S1-T13-4/main/pull/37[#37],
link:https://github.com/CS2103-AY1819S1-T13-4/main/pull/121[#121],

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
//include::../UserGuide.adoc[tag=savingdata]
Note: Since my main feature is non-interactive, most of my contributions to the User Guide involve refining existing sections by team members. 
== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

//include::../DeveloperGuide.adoc[tag=designstorage]


