= Teo Jia Jun - Project Portfolio
:site-section: AboutUs
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets

[discrete]
= PROJECT: ThanePark

---

== Overview

This portfolio serves to document my contributions to ThanePark.
ThanePark is a project that I have done in my software engineering module(CS2103T), in year 2, semester 1.
It is a desktop application used for theme park operators to manage their rides.

A limitation set by the module is that the user has to interact with ThanePark using a Command Line Interface(CLI).
It also has a Graphical User Interface(GUI) created with JavaFX.
ThanePark is written in Java, and has about 10,000 lines of code.

My task in ThanePark is to implement the view status command to view rides of different statuses and to update documents.


== Summary of Contributions

* *Major enhancement*: added the `viewstatus` command
** What it does: allows the user to obtain a list of rides filtered by the statuses of the rides.
** Justification: Allows the user to find relevant rides with ease.
** Highlight: This enhancement involved introduction a new predicate class, `RideStatusPredicate`,
  to allow users to input a fixed set of statuses to compare values with the existing data.
** Credits: The view status feature is based on the way find feature works, with a `RideStatusPredicate` instead of a
            `RideContainsKeywordsPredicate`.

* *Minor enhancement*:

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide.
They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=viewstatus]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=viewstatus]

