= Kok Jian Yu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: OASIS

---

== Overview

Office Assistance Specialized Integration System (OASIS) is for those who prefer to use a desktop app for managing employees, while allowing employees to handle some automatic features themselves.

== Summary of contributions

*Enhancement*: added *the ability to control the operations each employee can perform* through usage of Permissions.

NOTE: This operation can only be executed by an employee with `ASSIGN_PERMISSION` permission

** What it does: Ensures that each operation is executed by an employee with the permission required for it.
** Justification: There are many operations in OASIS that should only be performable by employees with certain authorization. Usage of permission allows the admins to easily ensure that previously stated criteria is met.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

*Enhancement*: added *the ability to modify the permissions granted to an employee*

NOTE: This operation can only be executed by an employee with `ASSIGN_PERMISSION` permission

** What it does: Modify the permissions of the employee.
** Justification: Allows for easy modification of permission
** Highlights: []
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

*Enhancement*: added *the ability to view the permissions granted to an employee*

NOTE: This operation can only be executed by an employee with `ASSIGN_PERMISSION` permission

** What it does: Display the list of permissions that an employee have.
** Justification: Users might not remember the permissions that have been assigned to an employee. This enhancement
give them a method to check it easily.
** Highlights: []
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

*Enhancement*: added *Command Auto-Complete* feature
** What it does: When user type in the command box, OASIS will predict the command that user is trying to execute, and
auto complete the command.
** Justification: This features also allows the user to be more productive, as they can save time on typing the commands.
** Highlights: []
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_


* *Minor enhancement*: [Add something here]

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

//include::../UserGuide.adoc[tag=undoredo]

//include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

// include::../DeveloperGuide.adoc[tag=undoredo]

// include::../DeveloperGuide.adoc[tag=da/taencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
