= Cai Jiaxiu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the achievements mechanism*
** What it does: Keeps track of the achievement information of the user and displays it on the UI.
** Justification: This enhancement lays down the basic infrastructure for the gamification component of the gamified task manager. The achievement information provides users with
incentive and motivation to complete the tasks. Daily and weekly achievement information also helps users keep track of their performances across time.
** Highlights: As the achievement information is updated per completion of task, the design of the mechanism needs to take into consideration of the undo/redo of complete commands. In depth analysis of alternative designs
is required to support such integration to keep the achievement information consistent with the actual completion of tasks. +
The support for daily, weekly achievement information also requires the achievement mechanism to have a sense of time to update and reset such time based achievement fields. +
As the achievement information is presented on the GUI rather than via the CLI on achievement commands. Design considerations are also required
to toggle back the achievement panel GUI display (e.g. from all-time to today) on undo/redo command. +
The whole mechanism requires extensive support and modification of all of the model, storage, logic and UI components of the existing software.

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=jiaxiu11[All code]].

* *Other contributions*:

** Project management:
*** Managed release `v1.4` on GitHub.
** Enhancements to existing features:
*** Added a status field to the tasks to different between in-progress, completed and overdue tasks.
*** Refactored the model component of address book to task manager.
** Documentation:
*** Overseeing UserGuide, formatted UserGuide and added in the unmodified features from the original software.
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-F11-3/main/pull/147[#147]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/130[#130],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/67[#67],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/141[#141],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/42[#42].

*** Reported bugs and suggestions for other teams in the class:
https://github.com/CS2103-AY1819S1-F10-4/main/issues/240[240],
https://github.com/CS2103-AY1819S1-F10-4/main/issues/236[236],
https://github.com/CS2103-AY1819S1-F10-4/main/issues/228[228].

** Tools:
*** Integrate Netlify to team repo.

_{you can add/remove categories in the list above}_

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=achievements]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=achievements]
