= Eric Yang Jia Wei - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Hallper

---

== Overview

The purpose of this portfolio is to document the contribution done to the project and provide an overview of what the
 project is about.

Our project is Hallper. Hallper is a desktop application targeting the Junior Common Room Committee (JCRC), a
management committee in the Halls of National University of Singapore. Hallper aims to put email, calendar and
finance management all in the same place. Hallper combines various applications into one, and allow the user to do
the different tasks at the same place.

Users key in commands to do tasks such as creating email, creating calendar event and viewing of each
CCA's transaction history.

== Summary of contributions

* *Major enhancement 1*: added *the budget feature*
** What it does: It allows the user to add budget to the CCAs and add on transactions in the future to keep track of
each CCA's spending.
** Justification: This feature improves Hallper's functionality as it provides an extra feature that can help user to
 manage the finance of his organisation. It provides a centralised place where the user can update and view each
 CCA's spending easily.
** Highlights: The budget feature adds on to the existing address book and creates a separate budget book to store
the information of the CCAs, their budget and finance. The tags used in the address book are used to indicate the
person's CCAs. The budget features also require in-depth understanding of the source code as it adds and deletes CCAs
and transactions, similar to adding and deleting a person in an address book.

* *Major enhancement 2*: added *the budget window*
** What it does: It is a window that display the list of CCAs available and each CCA's transaction history.
** Justification: This feature improves the user experience as the user can obtain the finance information of each
CCA easily. The separate window allows the user to go back to the main Hallper window easily when he wants to look up
 for a person in the address book. The separate windows enable the user to handle the finance and person look up at
 the same time, instead of switching between the address book and budget book.
** Highlights: This budget window requires a deep understanding of JavaFX and XML, and how they work together. It is
challenging as it requires interaction with the main window.

* *Minor enhancement*: added a F2 button to allow the user to switch between the budget window and the main Hallper
window.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Updated the About Us: _#to be added#_
*** Arrange the command in alphabetical order: https://github.com/CS2103-AY1819S1-W16-1/main/pull/113/commits/59679dc3edf8c607b42ed6fd02889aa79d8f7152[#113]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#113])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=add_cca]
include::../UserGuide.adoc[tag=delete_cca]
include::../UserGuide.adoc[tag=add_trans]
include::../UserGuide.adoc[tag=delete_trans]
include::../UserGuide.adoc[tag=update_cca]
include::../UserGuide.adoc[tag=budget]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=budget]
include::../DeveloperGuide.adoc[tag=add_cca]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
