= Jonathan Tan Jit Ming - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ExpenseTracker

---

== Overview

This portfolio aims to document the contributions made by *Jonathan Tan Jit Ming* to the *ExpenseTracker*.

*ExpenseTracker* is a desktop expense tracking application developed to aid users in tracking their expenses and
save money. The user interacts with it using a Command Line Interface (CLI), and it has a Graphical User Interface
(GUI) created with JavaFX library. It is written in Java, and has about 20 kLoC.

Some of its main features are:

. Setting a budget for expenses.
. Multiple user accounts.
. Categorization of expenses.
. Statistics for expenses.

== Summary of contributions

* *Major enhancement*: added *the ability for statistics of expenditures to be shown.*
** What it does: displays statistics of a user's expenditure by time and category in the form of a bar chart or pie chart.
** Justification: This is a core feature as it allows the user to be informed about their spending patterns over a period
of time or based on category
** Highlights: This feature required an in-depth understanding of the software architecture as it involves multiple
components of the application.

* *Minor enhancement*:

. Added a `Date` class that is used by `Expense`, which allows dates to be stored and compared.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** In charge of documentation for the team.
** Documentation:
*** Updated the User and Developer Guide. Improved language, formatting and structure: https://github.com/CS2103-AY1819S1-T12-1/main/pull/65[#65],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/66[#66], https://github.com/CS2103-AY1819S1-T12-1/main/pull/68[#68],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/89[#89], https://github.com/CS2103-AY1819S1-T12-1/main/pull/90[#90]
** Community:
*** Reviewed PRs: https://github.com/CS2103-AY1819S1-T12-1/main/pull/72[#72],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/73[#73], https://github.com/CS2103-AY1819S1-T12-1/main/pull/76[#76],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/91[#91], https://github.com/CS2103-AY1819S1-T12-1/main/pull/94[#94],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/98[#98], https://github.com/CS2103-AY1819S1-T12-1/main/pull/109[#109],

//*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=statistics]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=statistics]


