= Joshua Robert - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: OASIS
 ---
== Overview
Office Assistance Specialized Integration System (OASIS) is for those who prefer to use a desktop app for managing employees, while allowing employees to handle some automatic features themselves.
 This project portfolio summarizes the contributions that I have to the project.

== Summary of contributions
* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=jroberts91[Link to reposense]]

* *Major enhancement*: Added *the ability to archive and restore employees*
** Added *the ability to delete active employees and archive them*
*** Behaviour:
Allows a user with `Delete_employee` permission to delete an active employee and send it to the archive list.

*** Justification:
This feature improves OASIS significantly as it mimics firing of employees and keeping their information which is an important aspect of employee management.

*** Highlights:

** Added *the ability to restore employees*
*** Behaviour:
Allows a user with `Restore_employee` permission to restore an archived employee and send it to the active list.

*** Justification:
This feature improves OASIS significantly as it mimics firing of employees and keeping their information which is an important aspect of employee management.

*** Highlights:

** Added *the ability to permanently delete archived employees*
*** Behaviour:
Allows a user with `Delete_employee` permission to permanently remove archived employee from the application.

*** Justification:
This feature improves OASIS significantly as it mimics firing of employees and keeping their information which is an important aspect of employee management.

*** Highlights:

* *Minor enhancements*:
** Added list picker in UI which allows the user to change data shown in person list panel by just clicking on the list picker.


* *Other contributions*:

** Project management:
*** Managed releases v1.1 - v1.2 on GitHub

** Enhancements to existing features:
*** Updated the GUI color scheme for every `Person` card (Pull requests https://github.com[#1])
*** Updated the GUI to show a `ListPicker` to toggle between active and archive list. (Pull requests)

** Documentation:
*** Input initial contents of User Guide: https://github.com[#1]
*** Updated class diagrams for `UI` and `Model` component in the Developer Guide.

** Community:
*** `Listpicker` menu feature that I added was adopted by several other class mates ()
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2103-AY1819S1-W12-3/main/issues/125[1], https://github.com/CS2103-AY1819S1-W12-3/main/issues/124[2], https://github.com/CS2103-AY1819S1-W12-3/main/issues/139[3],
https://github.com/CS2103-AY1819S1-W12-3/main/issues/135[4])

** Tools:
*** Integrated Travis CI, AppVeyor and Coveralls to the team repo

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=archive]
include::../UserGuide.adoc[tag=restore]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=archive]
include::../DeveloperGuide.adoc[tag=restore]
