= Lai Keen Lok - Project Portfolio
:toc:
:toc-title:
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

[discrete]
== PROJECT: Thane Park
:toc-placement: preamble
:sectnums:

---

== Overview

This portfolio is meant to document my contributions to this project Thane Park. +
Thane Park is a desktop application used for managing the rides and attractions in a theme park. The user interacts with
it using a Command Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX. It is written
Java and has about 10 kLoc. +
My role in the project is to manage the tests and storage in the application. I've also added and enhanced a couple of
features, namely Filter and Find.


== Summary of contributions

* *Major enhancement*: added *the ability to filter data entries stored in the application*
** What it does: Allows users to filter entries based on the conditions that they can input.
** Justification: This feature significantly improves the application because now, users don't need to know the exact number
or name of the ride that they want. They can simple specify a range and then the application will provide a list of entries
that is within the range specified.
** Highlights: This enhancement involved introduction a new predicate class, `RideContainsConditionPredicate`, to allow users to input a range of values to
compare values with the existing data. +
The attributes of the rides that contains numeric values are also abstracted out to create a new interface `Attribute` that
the classes `Maintenance` and `WaitTime` implement. This allows the implementation of the predicate class `AttributePredicate`,
which enables it to store the user input and compare the values with the `Maintenance` and `WaitTime` of a ride class.
** Credits: The filter is based on the way find feature works, with a `RideContainsConditionPredicate` instead of a
`RideContainsKeywordsPredicate`.

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Enhancements to existing features: Find can now search tags and addresses in addition to the names of the rides


_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=filter]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=filter]


//== PROJECT: PowerPointLabs
//
//---
//
//_{Optionally, you may include other projects in your portfolio.}_
