= Keith Fong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Car park Finder

---

== Overview

Car park finder is a desktop address book application to find HDB (Housing Development Board) car parks in Singapore.
It allows you to work with a *Command Line Interface (CLI)* to display a list of car parks with the convenience of simply typing.
If you *use the computer frequently* and *commute by driving*, you would find our application useful in helping you obtain various information about car parks.

== Summary of contributions

* *Major enhancement*: Modified the *find feature to search for partial words* and *ignore certain words*.
** What it does: Allows the user to search for partial instances of words without needed to type everything.
** Justification: This feature improves the product significantly because a user can type lesser and the app should provide the same data still.
** Highlights:  This enhancement affects the existing commands and commands to be added in the future. I also wrote extra code which allowed us to re-use in the future.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:
** Project management
*** Morphed the code from address book to car park.
*** Morphed the test cases from address book to car park.

** Enhancement of existing features:
*** Wrote additional test for existing features to increase coverage from

** Documentation:
*** Did cosmetics tweaks to existing contents of the User Guide:
(Pull requests: https://github.com/CS2103-AY1819S1-T09-4/main/pull/36[#36],
https://github.com/CS2103-AY1819S1-T09-4/main/pull/60[#60],
https://github.com/CS2103-AY1819S1-T09-4/main/pull/74[#74],
https://github.com/CS2103-AY1819S1-T09-4/main/pull/76[#76])

** Community:
*** PRs reviewed (with non-trivial review comments):

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]


** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===



== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===




== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
