= SHANNA LIM KENG WOON - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Hallper

---

_{#To be edited#}_

== Introduction

The purpose of this portfolio is to document my role in and contributions to the project Hallper.

*About Hallper:* Hallper is a desktop administration application used by Junior Common Room Committee (JCRC) members of
the halls of NUS that facilitates management of hall residents and events. Our team of 5 computer science students
decided to create Hallper by building upon the existing AddressBook Level 4 application to improve management
activities for JCRC members. The user interacts with Hallper using a Command Line Interface (CLI), and Hallper
information is displayed using a Graphic User Interface (GUI) created with JavaFX. The application is written in Java
and contains about 60k lines of code (LoC). Some of the main features include new features such as calendar, email and
budgeting, as well as enhancement features such as erase, search and clear commands.

*My role and contributions:* I was tasked to implement four features: clear, erase, import and export commands.
Every two weeks, I reviewed the milestones that were set before our team embarked on building Hallper, based on the
features I had to implement, so i could complete my assigned portion on time.
I also helped to review my team members’ codes to check for coding style errors and to keep myself updated with their
implementations.


== Summary of contributions

This section lists the major and minor enhancements I have contributed to building Hallper, as well as miscellaneous
contributions in other aspects of this project.

* *Major enhancement 1:* added the ability to *import* residents data to update Hallper
** What it does: This feature allows the user to import xml files from the computer to update resident information stored in
Hallper. The user can update information in various parts of Hallper based on the format of the imported file.
** Justification: This feature improves Hallper significantly as the user can mass update resident information using a single
command without having to key in the data one by one.
** Highlights: This enhancement is highly case-sensitive as it requires the format of the imported file to be strictly
followed for the data to be successfully read. However, more file formats can be added by future developers based on
the current implementation of this command.

* *Major enhancement 2:* added the ability to *export* residents data from Hallper
** What it does: This feature allows the user to export all residents data in Hallper to an xml file on the computer.
** Justification: This feature facilitates transporting of Hallper information across various devices, accompanied by
the import command. Residents information can also be extracted to the computer for viewing or usage outside of the
application.
** Highlights: This enhancement allows users to export the xml file to any valid directory on the computer.

* *Minor enhancement 1:* added the ability to *erase* CCAs from residents in Hallper
** What it does: This feature allows the user to erase specified CCAs from all residents in Hallper.
** Justification: This feature speeds up the reassigning of CCAs by facilitating mass CCA erasure. Users need not go
through the residents one by one to remove the target CCAs.
** Highlights: This enhancement is a prelude to the import feature as it clears CCAs of the residents for reassignment
later using the import feature.

* *Minor enhancement 2:* improved the ability to *clear* residents from Hallper
** What it does: This feature allows the user to clear residents associated with the specified CCAs or room number, or
to clear the entire database.
** Justification: This feature expands the functions of the existing clear command by allowing more flexible clearing
options. The original clear command only allowed for clearing the entire database.
** Highlights: This enhancement allows the user to clear residents under multiple keywords (ROOM, CCA) using just a
single command line as multiple keywords can be specified at once in any order.

* Code contributed:
{empty}[https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=kengwoon[Project Code Dashboard]]

* Other contributions:
** Documentation:
*** Updated commands for team members and myself in the User Guide.
*** Updated commands for myself in Developer Guide.
** Community:
*** Reviewed pull requests by team members at each milestone.


== Contributions to the User Guide

|===
|This section contains my contributions to the User Guide for Hallper.
It has been documented and worded to facilitate mastering of features by end-users.
|===

include::../UserGuide.adoc[tag=clearAll]

include::../UserGuide.adoc[tag=clear]

include::../UserGuide.adoc[tag=erase]

include::../UserGuide.adoc[tag=export]

include::../UserGuide.adoc[tag=import]

== Contributions to the Developer Guide

|===
|This section contains my contributions to the Developer Guide for Hallper.
It contains a technical documentation of my implementations of the features assigned to me as mentioned in the
introduction.
|===

include::../DeveloperGuide.adoc[tag=clear]

include::../DeveloperGuide.adoc[tag=erase]

include::../DeveloperGuide.adoc[tag=export]

include::../DeveloperGuide.adoc[tag=import]

== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
