= Kong Zijin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TheTracker (v1.4)

---

== Overview

This document is written for summarizing my contributions in the project TheTracker.

The Tracker (v1.4) is a desktop application that helps NUS students to monitor contacts, modules and occasions.
The Tracker is optimized for those who prefer to work with a Command Line Interface (CLI) while still having
the benefits of a Graphical User Interface (GUI). It is designed for programmers who are used to CLI
applications and are good at typing.

== Summary of contributions

* *Major enhancement*: Create edit features for `Module` and `Occasion` and do enhancement to the existing edit person command
** What it does: allows the user to edit a person, module or occasion by index
** Justification: This is one of the basic features of TheTracker, which allows a user to edit module and occasion in a
similar way of how he edits a contact.
** Highlights: This feature is necessary for a user to simultaneously maintain all three types of entries.
** Credits:
*** This enhancement requires the different lists to be handled independently, but with all actions tracked simultaneously (e.g. for undo/redo).
*** This enhancement is designed to fit the insert command (All the attendence list related to the edited entity will be updated simultaneously).

* *Minor enhancement*:
** Create the export function
*** What it does: allows the user to export user data to a specified file type at a specified location.
*** Highlights: This feature enhance user's experience to TheTracker. He can now raise a data communication (with import feature in coming v2.0) with the external world.
*** Credits: This enhancement requires the command to access storage access directly, and has restrictions on the file path user typed in.

** Implement the `Occasion` class and its related classes(`OccasionName`, `OccasionDate`, `OccasionLocation`)

* *Code Contributions* : https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=kongzijin&sort=displayName&since=2018-09-12&until=2018-11-12&timeframe=day&reverse=false&repoSort=true[Code]

* *Other contributions*:

** Project management:
*** Managed milestones for `v1.2` - `v1.4` on Github
**** Opened issues
**** Set up milestone deadlines, close issues accordingly on GitHub
** Enhancements to existing features:
*** Add related classes for `EditPersonCommand`, `EditModuleCommand` and `EditOccasionCommand` (Pull requests https://github.com/CS2103-AY1819S1-W10-1/main/pull/108[#108])
*** Write additional tests for existing features to increase coverage
(Pull requests
https://github.com/CS2103-AY1819S1-W10-1/main/pull/108[#108],
https://github.com/CS2103-AY1819S1-W10-1/main/pull/121[#121],
https://github.com/CS2103-AY1819S1-W10-1/main/pull/189[#189],
https://github.com/CS2103-AY1819S1-W10-1/main/pull/208[#208])
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-W10-1/main/pull/108[#108],
https://github.com/CS2103-AY1819S1-W10-1/main/pull/112[#112],
https://github.com/CS2103-AY1819S1-W10-1/main/pull/173[#173],
https://github.com/CS2103-AY1819S1-W10-1/main/pull/183[#183]
** Documentation:
*** Write user stories for v1.0
*** Updated AboutUs.adoc to match application design (Pull requests https://github.com/CS2103-AY1819S1-W10-1/main/pull/34[#34])
*** Did cosmetic tweaks to existing contents of the User Guide (Pull requests https://github.com/CS2103-AY1819S1-W10-1/main/pull/124[#124])
*** Did cosmetic tweaks to existing contents of the Developer Guide (Pull requests https://github.com/CS2103-AY1819S1-W10-1/main/pull/114[#114], https://github.com/CS2103-AY1819S1-W10-1/main/pull/84[#84])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=export]

include::../UserGuide.adoc[tag=import]
== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=personcd]

include::../DeveloperGuide.adoc[tag=edit]

include::../DeveloperGuide.adoc[tag=export]
