= Kong Zijin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to EditModule and EditOccasion commands*
** What it does: allow the user to edit all fields in a `module` or an `occasion`, similar to `editPerson`.
** Justification: This is one of the basic features of TheTracker, which allows a user to edit module and occasion in a
similar way of how he edit a person in his address book.
** Highlights: This feature affects existing commands and commands to be added in future. It required an rigorous implementation as it required changes to existing commands.
** Credits: `EditCommand` in the original AddressBook4_{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate
judgement of how much effort went into the feature}_

* *Minor enhancement*: Implement the `Occasion` class and its related classes(`OccasionName`, `OccasionDate`, `OccasionLocation`)

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed milestones for `v1.2` - `v1.5rc` (set milestone deadlines, close issues and milestones accordingly) on GitHub
** Enhancements to existing features:
*** Wrote additional tests for Undo/Redo command features to increase coverage (in progress)
*** Did cosmetic tweaks to existing contents of the User Guide
** Community:
*** PRs reviewed (with non-trivial review comments)
** Tools:
*** Integrated a third party library (Natty) to the project, eg: (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=edit]
include::../UserGuide.adoc[tag=undoredo]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../UserGuide.adoc[tag=supportforocassionandmodule]
include::../UserGuide.adoc[tag=edit]
include::../DeveloperGuide.adoc[tag=undoredo]
include::../UserGuide.adoc[tag=history]



== PROJECT: ORBITAL 2018

|===
|_Project Description
|===

In this Orbital Project, we designed a 2D-pixel-style music-adventure Unity game. It is played on iOS platform.


