= Sem Jing Han - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:pullURL: https://github.com/CS2103-AY1819S1-W16-2/main/pull


== PROJECT: SocialCare

---
:sectnums:
== Overview

This portfolio documents my involvement in the SocialCare project that was developed under the CS2103T (Software Engineering) module taken in the National University of Singapore (NUS).

SocialCare is a desktop application designed to serve the *volunteer and event management* needs of social welfare organizations.
The main aim of the project was to streamline manual and inefficient processes faced by administrators of such organizations.
Users primarily interact with the application using a Command Line Interface (CLI) with elements of a Graphical User Interface (GUI) to display information.

My primary role as a developer for SocialCare involved implementing *event management functions* as well as handling *extensive user interface improvements*.



== Summary of Contributions

* *Major enhancement*: added the ability to manage and display *event records*
** What it does: This feature allows the user to create and manage events that span a period of time.
** Justification: This feature improves the product significantly because a user is able to display and keep track of events by the organisation. This is a core requirement to the application as volunteers have to be assigned to events for basic operations.
** Highlights:
This enhancement is one of the major building blocks of the system and affects majority of the other components. It required an in-depth analysis of design alternatives. The implementation too was challenging as other components are dependent on this component.

* *Minor enhancement*: added an overview command that allows the user to have a statistical overview of existing volunteers and events.

* *Code contributed*: Here is a https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=kratious[link] to my code on the Project Code Dashboard.

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Applied upstream bug fix: link:{pullURL}/78/[#78]
** Enhancements to existing features:
*** Updated the user interface aesthetics and behaviour: link:{pullURL}/92/[#92], link:{pullURL}/158/[#158], link:{pullURL}/243/[#243]
** Documentation:
*** Did cosmetic tweaks to existing contents of the Developer Guide: link:{pullURL}/118/[#118], link:{pullURL}/128/[#128]
** Community:
*** PRs reviewed (with non-trivial review comments): link:{pullURL}/58/[#58], link:{pullURL}/72/[#72], link:{pullURL}/232/[#232]
*** Enquired about and resolved a team issue on the forum: https://github.com/nus-cs2103-AY1819S1/forum/issues/134[#134]
** Tools:
*** Integrated a new Github plugin (Coveralls) to the team repository


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=eventmanagement]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=eventmanagement]

include::../DeveloperGuide.adoc[tag=command-overview]

