= Sem Jing Han - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:pullURL: https://github.com/CS2103-AY1819S1-W16-2/main/pull


== PROJECT: SocialCare

---
:sectnums:
== Overview

This portfolio documents my involvement in the SocialCare project, under the CS2103T Software Engineering module in NUS.
The main scope of the module requires students to modify an existing application with an established code base
while applying proper software engineering practices.

SocialCare is a desktop application designed to serve the volunteer and event management needs of non-profit organizations.
Users primarily interact with the application using a Command Line Interface (CLI) with elements of a Graphical User Interface (GUI) to display information.

My contributions to the project focused on the event management features as well as improving upon the original GUI.


== Summary of Contributions

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=kratious[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.3` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI aesthetics and layout (Pull requests link:{pullURL}/92/[#92],link:{pullURL}/148/[#148])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests)
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): link:{pullURL}/58/[#58],
*** Contributed to forum discussions (examples:  )
*** Reported bugs and suggestions for other teams in the class (examples:  )
*** Some parts of the history feature I added was adopted by several other class mates ()
** Tools:
*** Integrated a third party library (Natty) to the project ()
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=eventmanagement]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=eventmanagement]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
