= ZHANG TIANYANG - Project Portfolio

:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Piconso

== Overview

Piconso - The Piconso is a command line image processing tool, supported by ImageMagick, and is built to handle all the image processing in a light weight and efficient way. Users are able to use command line to perform operations, and visualize the result in GUI which is powered by JavaFx.

Unlink other image processing tools, without a long term learning process, piconso aims to privides simple, strarightforward, and user-friendly features. Moreover, piconso can be mouse free, which woould be more confortable for designers and developers.

== Summary of contributions

* *Major morphing*:
** *Enable the use of Imagemagick*
*** What it does: It determine the current operating system, prepare the zipped pacakge of ImageMagick, unzipp and prepare the ImageMagick package.
*** Justification:This is important as Imagemagick is the core part behind the app, allowing the editing of the images.

** *The ability to apply the transformation to image*
*** What it does: It parses the arguments specified by user, validate the transforamtion and apply the transformation to images.
*** Justification: This feature improves the product significantly, because apply the transformations to the image is the main feature and purpose of piconso.
*** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation was challenging as it required changes to existing commands, preparing packages, and touching the external package and excutbale files.
*** Credits: _{The processing of images is done by ImageMagic by calling the executable file in the processbuilder}_+

** *The ability to customise transformation basing on the transformations currectly*
*** What it does: This feature allows user to design and apply their own transformation.
*** Justification: This feature improves the product significantly as well, because when doing image editing, multiple transformations are used all the time. With this feature, the image editing will be much more efficient.
*** Highlights: This enhancement also affects existing commands and commands to be added in future. The implementation was challenging as it need handle file creating, writing and accessing.

* *Minor enhancement*:
** *Add a save command that allows the user to save the transformation wanted.*
*** What it does: It allows users to save the changes to the current image to the disk.

* *Code contributed*: [https://github.com/CS2103-AY1819S1-T09-3/main/commits?author=lancelotwillow[All commits]] [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=lancelotwillow[Project Code Dashboard]]

* *Other contributions*:

** Project management:
*** Managed releases jar file v1.3, v1.3.1 on GitHub
*** Participating merging PRs, creating, handling issues.
** Documentation:
*** Add info to the User Guide and Developer Guide about the apply, create, save commands.
https://github.com/CS2103-AY1819S1-T09-3/main/pull/125[#125]
*** Uploading User Guide for transforamtion and save features.
https://github.com/CS2103-AY1819S1-T09-3/main/pull/177[#177]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S1-T09-3/main/pull/195[#195], https://github.com/CS2103-AY1819S1-T09-3/main/pull/128[#128]
*** Contributed to forum discussions (examples:  https://github.com/nus-cs2103-AY1819S1/forum/issues/131[#131], https://github.com/nus-cs2103-AY1819S1/forum/issues/167[#167])
*** Create demo usage of the command, for testing of other team mates.(Example command, has been removed now)
** Tools:
*** Integrated a third party library (ImageMagic) to the project (https://github.com[#42])

== Contributions to the User Guide
|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../UserGuide.adoc[tag=apply]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../DeveloperGuide.adoc[tag=apply]

