= ZHANG TIANYANG - Project Portfolio

---

:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Piconso

---

== Overview

Piconso - The Piconso is a command line image processing tool, supported by ImageMagick, and is built to handle all the image processing in a light and efficient way.

== Summary of contributions

* *Major morphing*: added *the ability to apply the transformation to image, customised transformation*
** What it does: use convert command to apply the transformation, use the create command to create a new transformation.
** Justification: This feature improves the product significantly because a user can apply the transformation he wants, customise and combine multiple transformations to save time.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation was challenging as it required changes to existing commands, touching the external package and excutbale files.
** Credits: _{the processing is done by ImageMagic by calling the executable file in the processbuilder}_

* *Minor enhancement*: added a save command that allows the user to save the transformation wanted.

* *Code contributed*: [https://github.com/CS2103-AY1819S1-T09-3/main/commits?author=lancelotwillow[All commits]] [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=lancelotwillow[Project Code Dashboard]]

* *Other contributions*:

** Project management:
*** Managed releases jar file v1.3, v1.3.1(3 releases) on GitHub
** Documentation:
*** Add info to the User Guide and Developer Guide about the conver, create, save commands.
https://github.com/CS2103-AY1819S1-T09-3/main/pull/125[#125]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#131], https://github.com[#124]
*** Contributed to forum discussions (examples:  https://github.com[131]
*** Some parts of the history feature I added was adopted by several other class mates
** Tools:
*** Integrated a third party library (ImageMagic) to the project (https://github.com[#42])

== Contributions to the User Guide

include::../UserGuide.adoc[tag=convert]
include::../UserGuide.adoc[tag=save]
include::../UserGuide.adoc[tag=create]

== Contributions to the Developer Guide

=== Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._


include::../DeveloperGuide.adoc[tag=convert]

include::../DeveloperGuide.adoc[tag=create]

include::../DeveloperGuide.adoc[tag=save]

== PROJECT: PowerPointLabs

