= Louiz Kim-Chan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: InsuRen

---

== Overview

'Ren' in Mandarin translates to 'person' or 'people', and true to our name, this app is all about managing one’s network of clients in an organized, efficient and intuitive manner. InsuRen is geared to the needs of the modern Insurance salesman, but anyone whose business is their strong rapport with their clients will find this to be an indispensable tool.

== Summary of contributions

* *Major enhancement*: added *the ability to edit client contact information by name*.
** What it does: Instead of having to edit contact info by using an index, you can edit contacts directly using their name, provided their name is distinguishable from all other names.
** Justification: This feature improves the product significantly because normally, editing requires scrolling or using `find` to filter the list first. Since we don't want the user to have to use the mouse, and we want to speed up processes, editing by name will help achieve the product's goals.
** Highlights: This enhancement extends the `edit` command and makes use of a new `Predicate` in a method to find a `Person` provided a unique identifier.
** Credits: Nil.

* *Minor enhancement*: Make the address, email and phone number fields `Optional`.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** [To be done]
** Enhancements to existing features:
*** [To be done]
** Documentation:
*** [To be done]
** Community:
*** [To be done]
** Tools:
*** [To be done]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=editByName]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=editByName]
