= Ong Ming Xian - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MeNUS

---

== Overview

*MeNUS* is an all-in-one restaurant management desktop app designed to help restaurant owners
and managers streamline the process of managing restaurants within National University of Singapore (NUS).
With this app, users can manage their menus, sales, and even reservations.

This portfolio showcases my contributions to this project.

== Summary of contributions
* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=m4dkip[RepoSense]
* *Major enhancement*: added the *Reservation Management* feature
** *What it does*: allows the user to manage a Reservations List using various commands
** *Justification*: It can be messy to manually manage restaurant reservations using pen and paper.
This feature enables a systematic way to manage reservations.
** *Highlights*: This project required me to communicate with my teammates to synchronize our different
management systems. It required an in-depth analysis of the underlying *MeNUS* architecture.

* *Minor enhancement*: Added a way to add a command alias(a shortcut) to each command to allow users to type commands faster:
https://github.com/CS2103-AY1819S1-F10-4/main/pull/41[#41]

* *Other contributions*:

** Project management:
*** TBU
** Enhancements to existing features:
*** TBU
** Documentation:
*** Wrote my feature descriptions in the User Guide and Developer Guide
*** Helped teammates edit language and phrasing in the User Guide and Developer Guide
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S1-F10-4/main/pull/114[#114]
** Tools:
*** TBU

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide.
They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=reservations]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide.
They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=reservations]

include::../DeveloperGuide.adoc[tag=ucreservations]
