= Ling Zhi Yu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:main: https://github.com/CS2103-AY1819S1-W14-3/main


== PROJECT: HealthBase

== Overview
 First sentence PPP details, introduce appropriately
 make clear so person does not have to ask unnecessary qn
 consistency in language structure

This portfolio details the contributions I made to the development of a desktop application, as part of a team-based NUS Software Engineering module,
CS2103T.

HealthBase is a lightweight and free desktop application, designed to reduce the mundane yet important administrative duties faced by hospital staff.
By automating the tedious and providing convenient features crafted for its users, HealthBase allows for efficient management of patients' information.

The application's capabilities complement the roles of nurses and doctors, so that they serve patients better.

All features can be easily accessed by simply typing short commands into an input field.
These features include (among others):

* Management of check-in/out status of patients
* Real-time management of the check-in/out status of patients
* Patient medication data entry and retrieval
* Patient medical history data entry and retrieval
* Patient dietary restriction(s) data entry and retrieval
* Patient visitor history data entry and retrieval
* Real-time management of the number of visitors any given patient has
* Patient appointment management for doctors

== Summary of Contributions

* *Major enhancement*: Added the functionality to record and view patients' past medical diagnoses
** What it does: Records a diagnosis entry into the medical history of a given patient. Each entry includes the diagnosis description, the name of the examining and a timestamp.
** Justification: This feature serves as the primary storage of important patient data, as adjudged by the examining doctor's assessment. Past diagnoses are easily viewed on the desktop application to provide quick access for the examining doctor.
//** Highlights: The feature is
//** Credits:

* *Minor enhancement*:

* *Code contributed*: [https://github.com/CS2103-AY1819S1-W14-3/main/commits?author=omegafishy[my commits]]
* *Other contributions*:
** Project management:
*** Spearheaded project planning and managed project scope as project leader
** Enhancements to existing features:
** Documentation:
*** Amended existing contents of documentation according : (Pull Request: {main}/pulls/130[#130])

** Community:
*** Managed organisation code repository as administrator.
*** Reviewed pull requests and provided feedback. (Pull Requests: {main}/pulls/121[#121], {main}/pulls/122[#122], {main}/pulls/127[#127])
*** Reported feature bugs discovered during system testing. (Pull Request: {main}/issues/131[#131])

** Tools:
*** Integrated Github Plugins (Coveralls, Travis CI)
*** Automated team documentation build on https://cs2103-ay1819s1-w14-3.github.io/main/index.html[GitHub Pages]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addmh]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=addmh]
