= Pang Jia Hao - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: U-Schedule

---

== Overview

U-Schedule is a desktop scheduler application, that is targeted towards
university students who want a way to manage their schedules. It allows
users to manage 2 types of events: Calendar Events, which are events
which one normally enters into a calendar, and ToDoListEvents, which are
tasks that the user wants to keep track of. The primary interface is
the command line, and the GUI is created with JavaFX.
U-Scheduler is written in Java, and has about 10kLoC.

== Summary of contributions

* *Major enhancement*: Added the GUI to display calendar events in a calendar.
** What it does:
Allows the user to view calendar events graphically,
as well as navigate around their timetable.

** Justification: This feature is a critical addition to a
scheduler product. Without a visual representation of a calendar,
the user would be relying on date and time strings,
which would be extremely non-user-friendly even when
in standard format.

** Highlights:
I designed a class to contain the third-party library for rendering
events as a calendar. The class acts as a wrapper around the calendar
and contains the logic for controlling the calendar. I implemented the
controls needed for navigating around the calendar GUI. I also implemented
quality of life features such as automatically navigating to show events
that the user selected, as well as opening a pop-up dialog when the user
double clicks on events in the calendar.

** Credits: Used jxtras.Agenda for rendering events visually.


* *Code contributed*:
** link:https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=pangjiahao&sort=displayName&since=2018-09-12&until=2018-11-12&timeframe=day&reverse=false&repoSort=true[RepoSense]


* *Other contributions*:

** Project management:
*** Helped with issue tracking.

** Enhancements to existing features:

*** Prototyped fuzzy search for finding events.
(https://github.com/CS2103-AY1819S1-T10-1/main/pull/48[#48])
**** Wrote an initial set of utility methods using the fuzzywuzzy library.
**** Modified the original find command to use fuzzy search.

*** Designed FsList (FilteredSortedList), a list that allows filtering
by multiple predicates and sorting all in one. (https://github.com/CS2103-AY1819S1-T10-1/main/pull/116[#116])

*** Improved TestApp to support the improved Find command and
the todo list.
(https://github.com/CS2103-AY1819S1-T10-1/main/pull/116[#116],
https://github.com/CS2103-AY1819S1-T10-1/main/pull/130[#130])

** Documentation:
*** Updated class diagrams in the Developer Guide:
(https://github.com/CS2103-AY1819S1-T10-1/main/pull/117[#117])

** Community:
*** PRs reviewed (with non-trivial review comments):
(https://github.com/CS2103-AY1819S1-T10-1/main/pull/20[#20],
https://github.com/CS2103-AY1819S1-T10-1/main/pull/39[#39],
https://github.com/CS2103-AY1819S1-T10-1/main/pull/69[#69],
https://github.com/CS2103-AY1819S1-T10-1/main/pull/131[#131])

** Tools:
*** Integrated a third party library (natty) to the project.
(https://github.com/CS2103-AY1819S1-T10-1/main/pull/48[#48])
*** Integrated a third party library (fuzzywuzzy) into the project.
(https://github.com/CS2103-AY1819S1-T10-1/main/pull/48[#48])
*** Integrated a third party library (jfxtras.Agenda) into the project.
https://github.com/CS2103-AY1819S1-T10-1/main/pull/58[#58])


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=calendar]

include::../UserGuide.adoc[tag=faq]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=calendardisplay]
