= Park Sang Jun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

PROJECT: Student Schedule Planner

---

== Introduction

[write what this project portfolio showcases]
[introduce SSP, who u made this project with, what was the project u morphed from like eg,loc, constraints u worked under, etc]
Student Schedule Planner is a desktop schedule planner application used by students for schedule planning. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.
[optional: write ur key contributions to this project]

== Summary of contributions

* *Major enhancement*: added *the ability to add recurring tasks*
** What it does: allows the user to add a recurring task by specifying the number of repeats and interval between each repeat.
** Justification: This feature gives convenience to users as users with to-do tasks that happen repeatedly (eg. weekly) will not have to manually add the same tasks over and over again.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a list overdue command that allows the user to view his/her overdue tasks.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Documentation:
*** Updated User Guide and Developer Guide
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
** Tools:
*** Integrated Github plugin (Travis CI) to the team repo


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addrepeat]

include::../UserGuide.adoc[tag=listoverdue]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=addrepeat]

include::../DeveloperGuide.adoc[tag=listoverdue]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
