= Ng Peng Nam Sean - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: WatchOver

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Coordinated releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Product Manager Role
***** Coordinated and facilitated meetings one to two times a week to ensure group is on track
***** Ensures that deadlines are completed on-time (all team milestones met at all milestones)
https://github.com/CS2103-AY1819S1-F11-3/main/issues/169[#169(1.3)]
https://github.com/CS2103-AY1819S1-F11-3/main/issues/124[#124(1.2)]
https://github.com/CS2103-AY1819S1-F11-3/main/issues/64[#64(1.1)]
*** Maintained Issue Tracker and addressed bug reports from Dry-PE
https://github.com/CS2103-AY1819S1-F11-3/main/issues[Issues Page]
*** Created and maintained project boards
https://github.com/CS2103-AY1819S1-F11-3/main/projects/1[1.1],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/2[1.2],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/4[1.3],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/5[1.4],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/3[2.0]


** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]

** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-F11-3/main/pull/76[#76 (Batch complete command)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/95[#95 (list filter)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/154[#154 (list filter)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/67[#67 (Complete command)]
*** Reported bug on module website
(examples:  https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/3[#3],
https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/2[#2])

** Tools:
*** Maintained a Github plugin (TravisCI) in team repo https://github.com/CS2103-AY1819S1-F11-3/main/pull/60[#60]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
