= Ng Peng Nam Sean - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: WatchOver
---
== Overview

OverWatch is a desktop task manager.

== Summary of contributions

* *Major enhancement*: Time and completion dependency
** What it does:
Users can add and remove dependencies between tasks:
1) to ensure that the right tasks are completed in order
2)the earliest due date among all tasks that are directly or indirectly dependent on a given task is
displayed for that given task (an effective due date)

** Justification:
Some tasks have complicated dependencies with other tasks hence the user would want to ensure that he or she completes the
tasks in the right order.
A useful information to have when deciding how to prioritise tasks is not just to look at the due date of a task but
also the earliest due date among all tasks that directly or indirectly dependent on the task.

** Highlights:
*** There were significant design choices that needed to be made to specify dependencies given that tasks are immutable. (i.e.
Assume that there are two tasks, task A and task B, where task A is dependent on task B. If I was to edit task B, task A
has to be recreated as the dependencies on task A has to reflect the dependency to the new task B object)
*** Dependency feature is strongly connected to

* *Code contributed*:
https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=pengnam[[Project Code Dashboard]]
https://github.com/CS2103-AY1819S1-F11-3/main/commits?author=pengnam[[Github Commits]]

* *Other contributions*:
** *Minor Enhancements:*
**** Minor Enhancement 1: Time-based status update (between IN PROGRESS and OVERDUE)
**** Minor Enhancement 2: Topological sort (`topoorder` command)

** *Bugs found in other team's code:*
Bugs not due to inaccurate documentation are listed here. Some are relatively major and difficult to find.
*** https://github.com/CS2103-AY1819S1-W17-4/main/issues/195[Non-unique tasks]
*** https://github.com/CS2103-AY1819S1-W17-4/main/issues/241#issuecomment-437561699[Files with changed names]

** *Project Management:*
*** Coordinated releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Product Manager Role
***** Coordinated and facilitated meetings one to two times a week
***** Ensures that deadlines are completed on-time (all team milestones met at all milestones)
*** Created and maintained all project boards

** Enhancements to existing features:
*** Enhanced the GUI by allowing it to display time until completion
[PR #219]

*** Did a significant amount of initial refactoring for the team:
[PR 41, 47, 48, 50, 51, 54, 66]

** Documentation:
*** Did cosmetic tweaks to existing contents of the Developer Guide
*** Actively maintained the Developer Guide

** Community:
*** Reported bug on module website
(examples:  https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/3[#3],
https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/2[#2])
*** PRs reviewed (with non-trivial review comments):
[PR 76, 95, 154, 67, 213, 241]

** Tools:
*** Maintained a Github plugin (TravisCI) in team repo https://github.com/CS2103-AY1819S1-F11-3/main/pull/60[#60]


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=dependency]

include::../UserGuide.adoc[tag=topoorder]

include::../UserGuide.adoc[tag=add]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../DeveloperGuide.adoc[tag=seanmanualtest]

include::../DeveloperGuide.adoc[tag=command]

include::../DeveloperGuide.adoc[tag=dependency]

include::../DeveloperGuide.adoc[tag=time]
