= Ng Peng Nam Sean - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: WatchOver

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Time and completion dependency
** What it does:
Users can add dependencies between tasks:
1) to ensure that the right tasks are completed in order 2)
the earliest due date among all tasks that are dependent on a given task is displayed for that given task (an effective due date)

** Justification:
Some tasks are have complicated dependencies with other subtasks, and the user might want to ensure that they complete the
tasks in the right order.
A useful information to have when deciding how to prioritise tasks is not just to look at the due date of a task but
also the earliest due date among all tasks that depend on the task.

** Highlights:
*** There were significant design choices that needed to be made to specify dependencies given that tasks are immutable. (i.e.
Assume that there are two tasks, task A and task B, where task A is dependent on task B. If I was to edit task B, taskA
has to be recreated as the dependencies on task A has to reflect the dependency on the new task B object).
*** Modelling the notion of time and how it is related and associated with time involved design pattern choices.
*** Both are elaborated in the Developer guide.


* *Code contributed*:

https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=pengnam[[Project Code Dashboard]]
https://github.com/CS2103-AY1819S1-F11-3/main/commits?author=pengnam[[Github Commits]]

* *List of major PRs*:
https://github.com/CS2103-AY1819S1-F11-3/main/pull/75[Dependency feature]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/130[Dependency toggle]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/144[Flag overdue]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/48[DueDate modelling]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/84[Dependency validity]

* *Other contributions*:
** *Minor Enhancements:*
**** Minor Enhancement 1: Time-based status update
***** What it does:
The Task Manager needs to update the status field accordingly when a task is completed or deleted.
***** Justification:
The status needs to be accordingly responsive. i.e. If I was to update a task that is IN-PROGRESS to a new due date that
is before current time, the status of the task needs to be flagged as OVERDUE. If I decide to update an overdue task with
a new due date that is after current time, the status of the task needs to be adjusted to IN-PROGRESS.
***** Highlights:
****** Appropriate dependencies objects have to be adjusted accordingly after edits/task completion because Tasks are designed
to be immutable.
****** This check has to be triggered at every command hence a significant design pattern had to be adopted for an elegant
and clean solution.

**** Minor Enhancement 2: Topological sort (`topoorder` command)
***** What it does:
User can display a list of tasks in order of their topology
***** Justification:
Aids the user in prioritising which task to complete.
***** Highlights:
https://github.com/CS2103-AY1819S1-F11-3/main/blob/master/src/main/java/seedu/address/model/DependencyGraph.java[Topological sort implementation]

** *Bugs found in other team's code:*
Bugs not due to inaccurate documentation are listed here. Some are relatively major and difficult to find.
*** https://github.com/CS2103-AY1819S1-W17-4/main/issues/195[Non-unique tasks]
*** https://github.com/CS2103-AY1819S1-W17-4/main/issues/241#issuecomment-437561699[Files with changed names]

** *Project Management:*
*** Coordinated releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Product Manager Role
***** Coordinated and facilitated meetings one to two times a week to ensure group is on track
***** Ensures that deadlines are completed on-time (all team milestones met at all milestones)
https://github.com/CS2103-AY1819S1-F11-3/main/issues/169[#169(1.3)]
https://github.com/CS2103-AY1819S1-F11-3/main/issues/124[#124(1.2)]
https://github.com/CS2103-AY1819S1-F11-3/main/issues/64[#64(1.1)]
*** Maintained Issue Tracker and addressed bug reports from Dry-PE
https://github.com/CS2103-AY1819S1-F11-3/main/issues[Issues Page]
*** Created and maintained project boards
https://github.com/CS2103-AY1819S1-F11-3/main/projects/1[1.1],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/2[1.2],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/4[1.3],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/5[1.4],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/3[2.0]


** Enhancements to existing features:
*** Enhanced the GUI by allowing it to display time until completion
https://github.com/CS2103-AY1819S1-F11-3/main/pull/219[#219]

*** Did a significant amount of initial refactoring for the team:
https://github.com/CS2103-AY1819S1-F11-3/main/pull/41[#41],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/47[#47],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/48[#48],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/50[#50],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/51[#51],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/54[#54],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/66[#66],

** Documentation:
*** Did cosmetic tweaks to existing contents of the Developer Guide:
*** Actively maintained the Developer Guide:
https://github.com/CS2103-AY1819S1-F11-3/main/pull/171[#171]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/216[#216]

** Community:
*** Reported bug on module website
(examples:  https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/3[#3],
https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/2[#2])
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-F11-3/main/pull/76[#76 (Batch complete command)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/95[#95 (list filter)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/154[#154 (list filter)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/67[#67 (Complete command)]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/213[#213 (Tests for achievements)]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/241[#241 (Task UI)]


** Tools:
*** Maintained a Github plugin (TravisCI) in team repo https://github.com/CS2103-AY1819S1-F11-3/main/pull/60[#60]


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=dependency]

include::../UserGuide.adoc[tag=topoorder]

include::../UserGuide.adoc[tag=add]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../DeveloperGuide.adoc[tag=command]

include::../DeveloperGuide.adoc[tag=dependency]

include::../DeveloperGuide.adoc[tag=time]
