= Ng Peng Nam Sean - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: WatchOver

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Dependency and Time
** What it does: Users can add dependencies between tasks to ensure that the right tasks are completed in order.
The UI will display the earliest DueDate among all tasks that a task is dependent on (includes task dependees of task dependees).
The time of the earliest due date among all its children and grand children is displayed in the UI.
** Justification:
A useful information to look at when deciding how to prioritise tasks is looking at not just the due date of a task, but
the earliest due date among all tasks that it depends on.
** Highlights:
There were significant design choices that needed to be made to specify dependencies.
Modelling Time and checks associated with time involved design pattern choices.
Both are elaborated in the Developer guide.


* *Code contributed*:

https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=pengnam[[Project Code Dashboard]]
https://github.com/CS2103-AY1819S1-F11-3/main/commits?author=pengnam[[Github Commits]]

* *List of major PRs*:
https://github.com/CS2103-AY1819S1-F11-3/main/pull/75[Dependency feature]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/144[Flag overdue]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/48[DueDate modelling]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/84[Dependency validity]

* *Other contributions*:


** Project management:
*** Coordinated releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Product Manager Role
***** Coordinated and facilitated meetings one to two times a week to ensure group is on track
***** Ensures that deadlines are completed on-time (all team milestones met at all milestones)
https://github.com/CS2103-AY1819S1-F11-3/main/issues/169[#169(1.3)]
https://github.com/CS2103-AY1819S1-F11-3/main/issues/124[#124(1.2)]
https://github.com/CS2103-AY1819S1-F11-3/main/issues/64[#64(1.1)]
*** Maintained Issue Tracker and addressed bug reports from Dry-PE
https://github.com/CS2103-AY1819S1-F11-3/main/issues[Issues Page]
*** Created and maintained project boards
https://github.com/CS2103-AY1819S1-F11-3/main/projects/1[1.1],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/2[1.2],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/4[1.3],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/5[1.4],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/3[2.0]


** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Did a significant anount of initial refactoring for team:
https://github.com/CS2103-AY1819S1-F11-3/main/pull/41[#41],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/47[#47],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/48[#48],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/50[#50],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/51[#51],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/54[#54],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/66[#66],

** Documentation:
*** Did cosmetic tweaks to existing contents of the Developer Guide: https://github.com[#14]
*** Actively maintained the Developer Guide:
https://github.com/CS2103-AY1819S1-F11-3/main/pull/171[#171]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/216[#216]

** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-F11-3/main/pull/76[#76 (Batch complete command)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/95[#95 (list filter)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/154[#154 (list filter)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/67[#67 (Complete command)]
https://github.com/CS2103-AY1819S1-F11-3/main/pull/213[#213 (Tests for achievements)]

*** Reported bug on module website
(examples:  https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/3[#3],
https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/2[#2])

** Tools:
*** Maintained a Github plugin (TravisCI) in team repo https://github.com/CS2103-AY1819S1-F11-3/main/pull/60[#60]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=dependency]

include::../UserGuide.adoc[tag=topoorder]

include::../UserGuide.adoc[tag=add]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../DeveloperGuide.adoc[tag=dependency]

include::../DeveloperGuide.adoc[tag=time]

