= Ng Peng Nam Sean - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: WatchOver

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Dependency, Time
** What it does: Users can add dependencies between tasks to ensure that the right tasks are completed in order. Users can order tasks by their dependencies.
The time of the earliest due date among all children is displayed in the UI.
** Justification: This feature improves the product significantly because a user can better prioritise which task to
** Highlights: There were significant design choices that needed to be made to specify dependencies (elaborated in Developer Guide).


* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*:

https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=&sort=displayName&since=2018-09-12&until=2018-11-08&timeframe=day&reverse=false&repoSort=true[[Project Code Dashboard]]
https://github.com/CS2103-AY1819S1-F11-3/main/commits?author=pengnam[[Github Commits]]

* *Other contributions*:

** Project management:
*** Coordinated releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Product Manager Role
***** Coordinated and facilitated meetings one to two times a week to ensure group is on track
***** Ensures that deadlines are completed on-time (all team milestones met at all milestones)
https://github.com/CS2103-AY1819S1-F11-3/main/issues/169[#169(1.3)]
https://github.com/CS2103-AY1819S1-F11-3/main/issues/124[#124(1.2)]
https://github.com/CS2103-AY1819S1-F11-3/main/issues/64[#64(1.1)]
*** Maintained Issue Tracker and addressed bug reports from Dry-PE
https://github.com/CS2103-AY1819S1-F11-3/main/issues[Issues Page]
*** Created and maintained project boards
https://github.com/CS2103-AY1819S1-F11-3/main/projects/1[1.1],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/2[1.2],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/4[1.3],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/5[1.4],
https://github.com/CS2103-AY1819S1-F11-3/main/projects/3[2.0]


** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]

** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-F11-3/main/pull/76[#76 (Batch complete command)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/95[#95 (list filter)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/154[#154 (list filter)],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/67[#67 (Complete command)]
*** Reported bug on module website
(examples:  https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/3[#3],
https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/2[#2])

** Tools:
*** Maintained a Github plugin (TravisCI) in team repo https://github.com/CS2103-AY1819S1-F11-3/main/pull/60[#60]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=dependency]

include::../UserGuide.adoc[tag=topoorder]

include::../UserGuide.adoc[tag=add]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../DeveloperGuide.adoc[tag=dependency]

include::../DeveloperGuide.adoc[tag=time]

