= Pratyay Jaidev - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: EventsPlus+

---

== Overview

EventsPlus+ is a desktop address book application catered for busy university students to manage their contacts, events, project meetings and ad-hoc events efficiently.
EventsPlus+ aims to simplify some of the more time-consuming administrative tasks such as coordinating location and date of ad-hoc events
using a Command Line Interface (CLI). The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=pratyayj[RepoSense]]
* *Major enhancement*: added *location-related functionality*
** What it does: The two features added provide the following: 1. the ability to visually display the faculty location of a contact on a map and 2. the ability to generate a (random) meeting location
for events or meetings and display this location on a map.
** Justification: Events cannot take place without a location set in place. Adding location-related functionality with respect to a contact's faculty and events
improves the user experience significantly by providing the user one-stop location functionality without having to exit the application at all.
** Highlights: A Faculty field is added to the Person class which is crucial given that this application is primarily targeted toward university students.
The selection of which particular Google Maps API that was to be integrated into the application required careful consideration (the Embed API was chosen for its flexibility with the JavaFX web browser).
In the long run, the implementation of this foundational functionality allows for further development of other location-related features such as generating
directions or generating convenient meeting locations (based on faculty locations) which is one of the features to be done in V2.0.
** Credits: Google Maps Embed API was used for the map display.


* *Other contributions*:
** Minor enhancements:
*** Added a separate Location Display tab to display location-related information instead of using pre-existing Webpage tab.
(Pull request https://github.com/CS2103-AY1819S1-W13-2/main/pull/134[#134])

** Project management:
*** Managed release `v1.3.1` on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Added non-functional requirements to DeveloperGuide:
(Pull request: https://github.com/CS2103-AY1819S1-W13-2/main/pull/69[#69])
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
