= Pratyay Jaidev - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: EventsPlus+

---

== Overview

EventsPlus+ is a desktop address book application catered for busy university students to manage their contacts, events, project meetings and ad-hoc events efficiently.
EventsPlus+ aims to simplify some of the more time-consuming administrative tasks such as coordinating location and date of ad-hoc events
using a Command Line Interface (CLI). The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=pratyayj[RepoSense]]
* *Major enhancement*: added *location-related functionality*
** What it does: The two features added provide the following: 1. the ability to visually display the faculty location of a contact on a map and 2. the ability to generate a (random) meeting location
for events or meetings and display this location on a map.
** Justification: Events cannot take place without a location set in place. Adding location-related functionality with respect to a contact's faculty and events
improves the user experience significantly by providing the user one-stop location functionality without having to exit the application at all.
** Highlights: A Faculty field is added to the Person class which is crucial given that this application is primarily targeted toward university students.
The selection of which particular Google Maps API that was to be integrated into the application required careful consideration (the Embed API was chosen for its flexibility with the JavaFX web browser).
In the long run, the implementation of this foundational functionality allows for further development of other location-related features such as generating
directions or generating convenient meeting locations (based on faculty locations) which is one of the features to be done in V2.0.
** Credits: Google Maps Embed API was used for the map display.


* *Other contributions*:
** Minor enhancements to existing features:
*** Added a separate Location Display tab to display location-related information instead of using pre-existing Webpage tab:
(Pull request https://github.com/CS2103-AY1819S1-W13-2/main/pull/134[#134])
*** Application opens maximized at launch:
(Pull request https://github.com/CS2103-AY1819S1-W13-2/main/pull/176[#176])


** Project management:
*** Managed release `v1.3.1` on GitHub
*** Managed issue tracker and helped close issues upon completion: (examples: https://github.com/CS2103-AY1819S1-W13-2/main/issues/152[152],
 https://github.com/CS2103-AY1819S1-W13-2/main/issues/170[170])


** Documentation:
*** Added non-functional requirements to Developer Guide:
(Pull request: https://github.com/CS2103-AY1819S1-W13-2/main/pull/69[#69])
*** Edited and formatted use cases in Developer Guide:
(Pull request: https://github.com/CS2103-AY1819S1-W13-2/main/pull/172[#172], https://github.com/CS2103-AY1819S1-W13-2/main/pull/190[#190])


** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S1-W13-2/main/pull/177[#177], https://github.com/CS2103-AY1819S1-W13-2/main/pull/183[#183]
*** Reported bugs and suggestions for other teams in the class:
(examples:  https://github.com/CS2103-AY1819S1-T13-1/main/issues/134[134], https://github.com/CS2103-AY1819S1-T13-1/main/issues/142[142],
 https://github.com/CS2103-AY1819S1-T13-1/main/issues/144[144], https://github.com/CS2103-AY1819S1-T13-1/main/issues/159[159])


** Tools:
*** Integrated Google Maps API into to the project: (Pull request: https://github.com/CS2103-AY1819S1-W13-2/main/pull/134[#134])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=showFacultyLocation]
include::../UserGuide.adoc[tag=suggestedMeetingLocation]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=showFacultyLocationDisplay]
include::../DeveloperGuide.adoc[tag=generateMeetingLocation]

