== Note

This is a template for a portfolio, copied from the original AB4 fork.

---

= Vignesh Shankar - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Extended List to allow viewing of tasks that are due before a certain date, or have no dependency
** What it does: Allows the user to
*** list tasks that have a "due date" before certain points in time relative to
the current time, e.g the end of the day or the end of the week.
*** list tasks that do not have any uncompleted dependencies.
** Justification: This feature ties in with the overall goal of the product, as users can manage their tasks better --
they can see what tasks need to be done in a given time span, or see what tasks are not blocked by other dependencies.
** Highlights: This command is able to extend the functionality of the original List command without causing many changes
to other parts of the codebase. The only dependencies would be formed by the predicates created for the command. Working with
time-based comparison (and testing) was very challenging.

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=remo5000[RepoSense]]

* *Other contributions*:

** Project management:
*** Managed release `v1.2` on GitHub
** Enhancements to existing features:
*** Refactored the storage component of address book to fit task manager.
** Documentation:
*** Refactored About Us page and added scaffolds for project portfolios
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-F11-3/main/pull/60[#60],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/35[#35]

*** Reported bugs and suggestions for other teams in the class:
https://github.com/CS2103-AY1819S1-T13-2/main/issues/99[99],
https://github.com/CS2103-AY1819S1-T13-2/main/issues/94[94],
https://github.com/CS2103-AY1819S1-T13-2/main/issues/91[91],
https://github.com/CS2103-AY1819S1-T13-2/main/issues/98[98]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=list-usage]

== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
