= Reuben Tan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: modsUni

---

== Overview

modsUni is a desktop timetable management application created by students for students. It incorporates a simple GUI with majority of its user interactions occuring in its in-built CLI.

== Summary of contributions

* *Major enhancement*: **Generating** of a student's schedule was added.
** What it does: It allows students to generate a list of modules to take in each semester.
** Justification: This feature allows students to easily plan their candidature and it is also one of the
core features of modsUni.

* *Minor enhancement*: Loading in of modules from a `XML` file.
** What it does: It reads an `XML` file containing the list of modules that are available for students to
take.
** Justification: This feature allows students to view the module information and add it to their
staged/taken list for the generating of their schedule.

* *Code contributed*:

* *Other contributions*:

** Project management:
** Enhancements to existing features:
** Documentation:
** Community:
** Tools:

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=generate]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=generate]
