= John Doe - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: EventsPlus+

---

== Overview

EventsPlus+ is a Command Line Interface (CLI) desktop address book application catered for busy university students to
manage their contacts, events, project meetings and ad-hoc events efficiently.
It aims to simplify some of the more time-consuming administrative tasks
such as coordinating location and date of ad-hoc events.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has more than 10 kLoC.

== Summary of contributions

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=ryantanwk[RepoSense]]
* *Major enhancement*: added the *Notification/Favourite feature*
** What it does: Allows the user to enable/disable a welcome notification upon application startup. 
Moreoever, users can favourite an event so that the welcome message will display details of the event.
** Justification: Busy users should have a convenient means to remind themselves of an upcoming event.
** Highlights: If a favourite event is deleted, and notification is enabled,
the welcome notification will display a default welcome message instead of the events of a deleted event.

//~
* *Other contributions*:
** added *the toggle command*
*** What it does: CLI command which allows user to switch UI tabs.
*** Justification: Allow proficient users to navigate the UI solely using CLI.

** Project management:
*** Setup "About Us" documentation
*** Managed releases `v1.3` on GitHub

** Enhancements to existing features:
*** Added the notification / favourite / toggle functionalities and tests. (Pull requests https://github.com/CS2103-AY1819S1-W13-2/main/pull/89[#89],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/90[#90],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/103[#103],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/115[#115],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/128[#128],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/135[#135],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/194[#194]

** Documentation:
*** Updated documentation for the enhancements as above: (Pull requests https://github.com/CS2103-AY1819S1-W13-2/main/pull/103[#103],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/115[#115],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/128[#128],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/135[#135],
  https://github.com/CS2103-AY1819S1-W13-2/main/pull/194[#194],

** Community:
*** Reported bugs and suggestions for other teams in the class (https://github.com/CS2103-AY1819S1-W17-3/main/issues/101[1], 
  https://github.com/CS2103-AY1819S1-W16-1/main/issues/103[2], 
  https://github.com/CS2103-AY1819S1-W17-3/main/issues/105[3],
  https://github.com/CS2103-AY1819S1-W17-3/main/issues/112[4],
  https://github.com/CS2103-AY1819S1-W17-3/main/issues/118[5],
  https://github.com/CS2103-AY1819S1-W17-3/main/issues/122[6]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
include::../UserGuide.adoc[tag=notification]
include::../UserGuide.adoc[tag=favourite]
include::../UserGuide.adoc[tag=toggle]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=notification]
include::../DeveloperGuide.adoc[tag=favourite]
include::../DeveloperGuide.adoc[tag=toggle]

