= Thangavel Sharan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: _SocialCare_

---

== Overview
This project portfolio page serves to document my contributions to _SocialCare_, a software engineering project that was
undertaken as part of the National University of Singapore (NUS) School of Computing's beginner Software Engineering
module, CS2103T. More information on this module can be found
https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/index.html[here].

_SocialCare_ is an *event and volunteer management system* for social welfare organisations, which runs on desktops.
The user interacts with it using the Command Line Interface (CLI), and it has a Graphical User Interface (GUI)
created using https://docs.oracle.com/javafx/2/overview/jfxpub-overview.htm[JavaFX]. The application is written in Java,
and has about 10,000 lines of code.

Key Features of _SocialCare_:

* Add, remove and store volunteers and events.
* Assign volunteers to events.
* Create event records for each volunteer consisting of the event and volunteer IDs, hours contributed and related
remarks.
* Export a PDF certificate detailing a volunteer’s involvement with the organisation (event records, contributed hours).

Through the use of the CLI, _SocialCare_ enables the above functionalities to be executed faster than a typical
mouse/GUI driven application.

== Summary of contributions

* My *code contributed* can be found
https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=sharan8[here].
* *Major enhancement*: I added *the ability to export volunteer certificates in PDF format.*
** _What it does_: This feature allows the user to export a volunteer’s event records and contributed hours in the form
of a PDF certificate.
** _Justification_: This feature improves the product significantly as it automates a task that is currently done
largely manually, and offers the user a way to access information from outside of the application as well (via portable
and printable PDF files).
** _Highlights_: This enhancement involved an in-depth analysis of available external open source libraries, and
meticulous design of the exported PDF document.
** _Credits_: This feature was developed with the use of https://pdfbox.apache.org/team.html[Apache PDFBox], which
provides the functionality to create and write to PDF files.

* *Minor enhancement*: I added the *total volunteer count to the status bar*. This enhancement is in line with our
application’s intention to provide the user with easy access to useful information pertaining to volunteers.

* *Code contributed (To be updated)*: [https://github.com[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Documentation:
*** Revised the introduction sections of the
https://github.com/CS2103-AY1819S1-W16-2/main/blob/master/README.adoc[README],
https://github.com/CS2103-AY1819S1-W16-2/main/blob/master/docs/UserGuide.adoc[User Guide] and
https://github.com/CS2103-AY1819S1-W16-2/main/blob/master/docs/DeveloperGuide.adoc[Developer Guide].
** Community:
*** Reviewed PRs (with non-trivial review comments): To be updated.
*** Contributed to forum discussions: To be updated.
** Tools:
*** Integrated a third party library (https://pdfbox.apache.org/index.html[Apache PDFBox]) to the project
(https://github.com/CS2103-AY1819S1-W16-2/main/pull/161[#161]).
** Project conceptualisation:
*** Set up a shared
https://docs.google.com/document/d/19iV64xK0EwaV8kjMaP72P1G7iGKKXtEX2my5M-QowKc/edit?usp=sharing[Brainstorming Canvas]
to brainstorm on product morphing ideas using the 'Target User Profile-Problem-Value Proposition' framework.
*** Conceptualised and validated the idea for _SocialCare_ through conversing with staff from 2
social welfare organisations that I have worked with in the past.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=exportcert]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=exportcert]
