= Jaime Chow Wen Juan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ExpenseTracker

---

== Overview

Expense Tracker is the secure, efficient financial application for the keyboard enthusiast. With features such as daily tips,
statistics and budget setting, Expense Tracker aims to provide users with the necessary tools to become a better saver.

This portfolio is a documentation of my contributions to the morphing of AddressBook into ExpenseTracker. I mainly worked on GUI overhauls, as well
as the implementation of a Automatic Notification System.

== Summary of contributions

*Major Enhancement:* Implementation of GUI elements for newly implemented features

* *What It Does*

** It displays the user's expenditure information on the GUI. This includes their notifications, monthly budget, monthly expenses and budgets for categories.
The Notification System in particular, was entirely implemented by me. This feature generates and displays daily saving tips and warnings
if the user is about to spend or have spent over their budget.

* *Justification*

** A well-designed and responsive user interface is able to maximize user experience and allows `Expense Tracker` to stand out amongst the sea
of financial applications.

** I believe that there will be a subset of user who use `Expense Tracker` because they are unable to maintain a budget. The Notification System aims to
help said users by facilitating in budget management and providing general knowledge about saving money.

* *Highlights*

** Creativity and many design considerations were required to get the Expense Tracker GUI to look and function as I had envisioned.
** Additional features animation and dynamic changing of text color were also implemented for the GUI for improved visual feedback.
** The implementation of the Notification System, in particular, was challenging as it involved making additions and modifications to all components of Expense Tracker.

*Minor enhancements*:

. Implemented the `notification` command that allows users to toggle automated notification sending.
. Implemented other minor Animations to existing features such fade-in effect upon login.
. Implemented panel switching. The leftmost panel of the GUI can swap between statistical information and the list of expenses.
. Completely Overhauled the CSS styling of the application.
. Added color to `Tags`.

*Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=jaime&sort=displayName&since=2018-09-12&until=2018-11-02&timeframe=day&reverse=false&repoSort=true[Reposense Compilation]

*Other contributions*:

** Documentation:
*** Updated the `Notification` component section of the User Guide: https://github.com/CS2103-AY1819S1-T12-1/main/pull/187[#187]
*** Updated the `Use Case`, `User Stories` and `User Interface` component section of the Developer Guide: https://github.com/CS2103-AY1819S1-T12-1/main/pull/187[#187], https://github.com/CS2103-AY1819S1-T12-1/main/pull/75/files[#75]
*** Made changes to the Developer Guide. Improved language and edited diagrams: https://github.com/CS2103-AY1819S1-T12-1/main/pull/187[#187], https://github.com/CS2103-AY1819S1-T12-1/main/pull/75/files[#75]

** Community:
*** Reviewed PRs (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-T12-1/main/pull/110[#110], https://github.com/CS2103-AY1819S1-T12-1/main/pull/175[#175],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/182[#182]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=notification]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=userinterfaceredesign]



