= Lim Yu Xi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: LostBUTFound

---

== Overview

LostBUTFound is a desktop application used for managing lost and found articles. Users will be able to manage the articles and view important information about them.

LostBUTFound has a graphical user interface built with JavaFX but most of the user interactions are done using command line interface. It is written in Java and has about 10 kLoC.

This portfolio summarizes my contributions for the development of LostBUTFound. It showcases the software engineering knowledge and that I have applied throughout the project.

== Summary of contributions

* *Major enhancement*: added *the ability to resolve articles*
** What it does: It allows the user to resolve articles once it have been claimed by the owner. Resolved articles would still be stored for logging purposes and can be deleted using the `delete` command, but they cannot be edited. Resolved articles would also not appear in the list unless the `findresolved` command is executed.
** Justification: This feature helps users keep track of both resolved and unresolved articles.

* *Minor enhancement*: added *the ability to find articles based on specific fields*
** What it does: It allows the user to search for articles depending on different fields and parameters.
** Justification: This features helps users find relevant articles quickly and easily.

* *Minor enhancement*: added *finder, owner, and isResolved attributes to Article*
** What it does: It allows the user to keep track of the person who found and claimed the article, and whether the article have been resolved.
** Justification: This features allows LostBUTFound to create a personalised experience for the user. Each article entry should contain all necessary information about the article.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=resolvefeature]

include::../UserGuide.adoc[tag=findfeature]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

//include::../DeveloperGuide.adoc[tag=user]
include::../DeveloperGuide.adoc[tag=find]
include::../DeveloperGuide.adoc[tag=resolve]


