= Syahiran Rafi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLInic

---

== Overview

Hello, I am Syahiran. I am currently in my third year in the National University of Singapore (NUS), where I am majoring in Computer Science (CS). As part of the Introduction to Software Engineering module (CS2103T), I worked with four other students from CS to modify and improve the given address book application into a database management system called CLInic.

CLInic is a desktop application, designed specifically for clinics. It helps to automate daily administrative tasks like:

* Easily maintaining and updating a database of patients and their medical records
* Checking and updating medicine inventory
* Generating receipts, medical certificates and referral letters

CLI is an acronym for "Command Line Interface", as CLInic works by typing commands directly into the application through the CLI. Together with CLInic's clean Graphical User Interface (GUI), the finished product allows for an easy and intuitive experience for both technical and non-technical users alike.

This project portforlio serves to document my contributions to this project, which you can find in the sections below.

== Summary of contributions

* *Major enhancement*: supported the implementation of the `*Document*` class, along with its accompanying
                       extending classes `MedicalCertificate` and `ReferralLetter`.
** What it does: takes in information like the duration of medical leave and referral notes by the doctor to generate the medical certificate and referral letter document respectively.
** Justification: this feature makes it easier to generate documents that need to be frequently generated in a clinic, reducing administrative duties for clinic staff and hopefully shortening wait times for patients.
** Highlights: this feature allows for a seamless transfer of information between doctors and clinic staff, as well as a fast retrieval of information from the application's database of `Patient` and `Medicine` information.


* *Minor enhancement*: added *shorthand codes or aliases* for most of the commands in CLInic to reduce the amount of typing necessary when using the CLI.
** Justification: Some commands like `dispenseMedicine` and `MedicalCertificate` are really long, so it can be troublesome for the user to type the whole command in order to execute the command.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
*** Edited the language, style and tone of the User Guide: https://github.com[#14]
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

. Implementation of the `MedicalCertificate` class

include::../DeveloperGuide.adoc[tag=mc]

[start = 2]
. Implementation of the `ReferralLetter` class

include::../DeveloperGuide.adoc[tag=referralletter]

