= Syahiran Rafi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CLInic

---

== Overview

Hello, I am Syahiran. At the time of writing, I was in my third year at the National University of Singapore (NUS), where I majored in Computer Science (CS). As part of the Introduction to Software Engineering module (CS2103T), I worked with four other students from CS to modify and improve the given https://github.com/nus-cs2103-AY1819S1/addressbook-level4[address book application] into a database management system called CLInic.

CLInic is a desktop application, designed specifically for clinics. It helps to automate daily administrative tasks like:

* Easily maintaining and updating a database of patients and their medical records
* Checking and updating medicine inventory
* Generating receipts, medical certificates and referral letters

CLI is an acronym for "Command Line Interface", as CLInic works by typing commands directly into the application through the CLI. Together with CLInic's clean Graphical User Interface (GUI), the finished product allows for an easy and intuitive experience for both technical and non-technical users alike.

This project portforlio serves to document my contributions to this project, which you can find in the sections below.

== Summary of contributions

* *Major enhancement*: I supported the implementation of the `*Document*` class, along with its accompanying
                       extending classes `MedicalCertificate` and `ReferralLetter`.
** What it does: This feature allows for the doctor to input information like the duration of medical leave and referral location to easily generate medical certificate and referral letter documents in the form of `HTML` files.
** Justification: This feature makes it easier to generate documents that need to be frequently generated in a clinic, *reducing administrative duties* for clinic staff and hopefully *shortening wait times* for patients.
** Highlights: This feature allows for a *seamless transfer of information* between doctors and clinic staff, as well as a fast retrieval of information from the application's database of `Patient` and `Medicine` information.


* *Minor enhancement*: I added *shorthand codes or aliases* for most of the commands in CLInic to reduce the amount of typing necessary when using the CLI.
** Justification: Some commands like `dispenseMedicine` and `MedicalCertificate` are really long, so it can be troublesome for the user to type the whole command in order to execute the command. Instead, users can type `dm` and `mc` to execute the same respective commands.

* *Code contributed*: View my code for the project https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=&sort=displayName&since=2018-09-12&until=2018-11-08&timeframe=day&reverse=false&repoSort=true[here]!

* *Other contributions*:

** Documentation:
*** Edited the language, style and tone of the User Guide: https://github.com/CS2103-AY1819S1-W16-4/main/pull/126[#126]
*** Added a Command Summary Table to the User Guide: https://github.com/CS2103-AY1819S1-W16-4/main/pull/129[#129]
** Community:
*** Reviewed PRs (with non-trivial review comments): https://github.com/CS2103-AY1819S1-W16-4/main/pull/115[#115]
** Enhancements to existing features:
*** Attempted to implement a discount feature for patients under health assistance schemes, but this shall be pushed to v2.0: https://github.com/CS2103-AY1819S1-W16-4/main/pull/176[#176]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=mc]
include::../UserGuide.adoc[tag=refer]
include::../UserGuide.adoc[tag=table]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=mc]
include::../DeveloperGuide.adoc[tag=referralletter]
