= Thaddeus - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Student Schedule Planner

---

== Overview

Student Schedule Planner (SSP) is a desktop application aimed at helping students manage their schedules
effectively. SSP is optimised for users who prefer to type in commands, instead of using a Graphical
User Interface(GUI). Given efficient typing, this application will be much faster than regular to-do
applications.

== Summary of contributions

* *Major enhancement*: added *the ability to filter tasks according to their tags*
** What it does: Allows the user to filter their tasks with respect to their tags. The filter
command is inclusive, which means that given 2 or more tags to filter, tasks with any, some, or all of the specified
tags will be listed.

** Justification: This feature improves the product significantly because a user can filter out tasks with a certain
tag, expediting the search process, and the app should provide a convenient way to list all these tasks.

** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth
 analysis of design alternatives. The implementation was challenging as it required the filter to be able to search
 for more than 1 tag in the tasks, which may contain more than 1 tag.
** Credits: Code from FindCommand was referenced in the implementation of FilterCommand

* *Major enhancement*: added *the ability to list the remaining number of tasks in the current month*
** What it does: Allows the user to list and view all the remaining tasks in the current month, in chronological
order. This feature takes into account leap years.

** Justification: This feature improves the product significantly because a user can now narrow the scope of the list
 to the current month, making it easier to manage his/her tasks. The app should provide a convenient way to list
 tasks within common time periods.

** Highlights: This enhancement does not affect existing commands and commands to be added in future. It required an
in-depth analysis of design alternatives. The implementation was challenging as it had to factor in the variations of
 total days in February during leap years.
** Credits: Code from ListWeekCommand was referenced in the implementation of ListMonthCommand

* *Minor enhancement*:

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
