= Chen Shaowei - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Cow

---

== Overview

Cow is a project management app with an emphasis on Command Line Interface ("CLI") interaction. It is written in Java, and its Graphical User Interface ("GUI") is created with JavaFX. It has approximately 10k LoC.

== Summary of contributions

* *Major enhancement*: added *the ability to visualise tasks in a calendar*
** What it does: allows the user to view all tasks due in a specified month through the `calendar show` command.
** Justification: This feature achieves a significant improvement in the task management workflow by allowing easier and more intuitive deadline management. The user would be able to visualise his tasks for the entire month via the calendar view instead of in a single list.
** Highlights: This enhancement involves significant changes to the GUI. It requires a good understanding of the tools available via JavaFX in order to both build the feature and test it. In addition, the implementation was challenging as it involved changes at multiple levels in the app.

* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=tuesmiddt[Collated code at RepoSense]

* *Other contributions*:

** Documentation:
*** Port Readme, User Guide, and Developer Guide sections from Markdown meeting minutes: https://github.com[#2]
** Community
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-T09-1/main/pull/160[#160]
** Tools
*** Introduced the use of PlantUML instead of PowerPoint for the generation of UML diagrams.

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=calendar]

include::../UserGuide.adoc[tag=calendarshow]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=calendarshow]
