== Note

This is a template for a portfolio, copied from the original AB4 fork.

---

= Jeffery Kwoh Ji Hui - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added the ability to *complete a task as identified by
index*, *complete a batch of tasks as identified by a label*.

** Complete a task as identified by index

*** What it does: allows the user to complete task in the task manager
*** Justification: This feature provides on of the core functionality of task
managers, marking a task as complete.

** Complete a batch of tasks as identified by a label

*** What it does: allows the user to complete a batch of task identified by
a label in the task manager atomically.
*** Justification: This feature allows for the user to convenient complete
multiple tasks at one go through the simple use of labels.
**** This present to them
a better user experience than monotonously completing tasks one by one.
**** Furthermore, as this operation is atomic to the user, if he makes a mistake in
completing the tasks he need only use the undo command once to revert changes
to the batch of tasks. He need not painstakingly undo them one by one.
*** Highlights: This enhancement required careful design considerations due to the
creation of two flavours of the complete command. Moreover, the atomicity
required from this feature required a model rollback operation that it does not
currently support. Moreover, this implementation was challenging as it required
changes to other components of the application.
**** Converting `CompleteCommand` into an abstract class in order to support the
polymorphic behaviour of the two flavour of completion. Additionally, this helps
keeps code organised neatly by following the Single Responsibility Principle.
**** Implementing a rollback operation for the model, which could possibly be
used to provide better data integrity of the application in future development.

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-F11-3/main/pull/31[#31],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/36[#36],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/37[#37],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/41[#41],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/70[#70],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/75[#75],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/78[#78],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/84[#84],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/114[#114],
https://github.com/CS2103-AY1819S1-F11-3/main/pull/144[#144]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated Travis CI to the team repo
*** Integrated Coveralls to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=complete-usage]

include::../UserGuide.adoc[tag=complete-2.0]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=complete]

== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
