= Way Tan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TheTracker (v1.4)

---

== Overview

This Project Portfolio details my contributions to TheTracker.
It demonstrates my ability to contribute as a team member of a software engineering project in both technical and non-technical ways.

== Summary of contributions

* *Major enhancement*: *Improved `delete` function to properly delete any type of entry*
** Description: Allows the user to delete a person, module or occasion by index. It also removes this entry from all other linked entries.
** Highlights: This enhancement has two aspects:
*** Inferred Deletion: The deletion will be applied to the currently active list.
*** Deep Deletion: The deletion will automatically all references to this entry (i.e. from other entries' lists)
** Design Considerations: Based on the current undo/redo implementation, new copies must be created for updated entries.

* *Minor enhancement*: Improved `select` function to handle the three lists
** Description: Allows the user to select an entry from the active list, and view additional info
** Importance: The implementation is symmetric across all 3 lists, so that the user does not need to use different commands for different lists.

* *Code Contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=waytan[Link to Code Contributions]

* *Other contributions*:

** Conceptualization:
*** Suggested context-inferring commands (e.g. `select`, `delete` instead of `selectmodule, `deletemodule`)
*** Suggested implementing `insertperson` and `removeperson` to link persons with modules/occasions
** Project management:
*** Involved in distributing roles and consolidating tasks
*** Manage Issue Tracker for v1.3, v1.4
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S1-W10-1/main/pull/81[#81], https://github.com/CS2103-AY1819S1-W10-1/main/pull/87[#87]
*** Methods written for implementation of deep deletion were adapted for edit and removeModule.
*** Set up test utils for modules and occasions: https://github.com/CS2103-AY1819S1-W10-1/main/pull/97[#97], https://github.com/CS2103-AY1819S1-W10-1/main/pull/109[#109]
*** Helped in identifying bugs and offered suggestions for debugging
** Documentation:
*** Wrote user stories, use cases for v1.0
*** Updated description of user guide to match application design
** Key Code Components
*** Set up `Module` class and its associated fields/exceptions


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=GUIComponents]
include::../UserGuide.adoc[tag=types]
include::../UserGuide.adoc[tag=delete]
include::../UserGuide.adoc[tag=select]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=explanationofpolymorphism]
