= Winson Heng Yong Seng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:relfileprefix: ../
:stylesDir: ../stylesheets

== PROJECT: ExpenseTracker

---

== 1. Overview

This portfolio aims to document the contributions that I made to the *ExpenseTracker*.

*ExpenseTracker* is a desktop expense tracking application developed to aid users in tracking their expenses and
saving money. The user interacts with it using a Command Line Interface (CLI), and it has a Graphical User Interface
(GUI) created with JavaFX library. It is written in Java, and has about 20k lines of code.

Some of its main features are:

. Setting a budget for expenses.
. Multiple user accounts.
. Categorization of expenses.
. Statistics for expenses.


== 2. Summary of contributions

This section highlights some of the contributions that I have made to Expense Tracker.

* *Major enhancement*: added *the ability to have a budget on expenses.*
** Function: It informs the user if the their spendings exceed a set budget
** Justification: This is a core feature as it allows the user to know when they are spending too much money, the
main purpose of an expense tracker.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth
 analysis of software design alternatives. The implementation was challenging as it required changes to existing
 commands and the existing implementation of the main `ExpenseTracker` class.

* *Minor enhancements*:

. Added a `setRecurrenceFrequency` command that allows the user to reset their available spending at a frequency of
their choice.
. Added a `setCategoryBudget` command that allows the user to set budgets based on their category of expenses.

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=winsonhys&sort=displayName&since=2018-09-12&until=2018-11-02&timeframe=day&reverse=false&repoSort=true[Code]]

* *Other contributions*:

** Project management:
*** Created the organisation repository, set up issue tracker and milestones.
** Documentation:
*** Updated the About Us document: https://github.com/CS2103-AY1819S1-T12-1/main/pull/2[#2]
*** Made changes to the Developer Guide. Improved language and edited diagrams:
https://github.com/CS2103-AY1819S1-T12-1/main/pull/74[#74]
** Community:
*** Reviewed PRs (with non-trivial review comments): https://github.com/CS2103-AY1819S1-T12-1/main/pull/6[#6],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/8[#8], https://github.com/CS2103-AY1819S1-T12-1/main/pull/9[#9],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/11[#11], https://github.com/CS2103-AY1819S1-T12-1/main/pull/20[#20],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/21[#21], https://github.com/CS2103-AY1819S1-T12-1/main/pull/22[#22],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/24[#24], https://github.com/CS2103-AY1819S1-T12-1/main/pull/31[#31],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/33[#33], https://github.com/CS2103-AY1819S1-T12-1/main/pull/45[#45],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/69[#69], https://github.com/CS2103-AY1819S1-T12-1/main/pull/71[#71],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/108[#108]
** Tools:
*** Created a script to pull code from main fork to local fork.
https://github.com/CS2103-AY1819S1-T12-1/main/pull/17[#17]


== 3. Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=budget]
For more details and caveats for this feature, please refer to the <<UserGuide#, user guide>>.

== 4. Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical
 documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=budgetPart1]
For more details on explanation on how Expense Tracker executes when a user sets a recurrence frequency and its
sequence diagram, please refer to the <<DeveloperGuide#recc-seq-diag, Developer Guide>>.

include::../DeveloperGuide.adoc[tag=budgetPart2]

==== Setting a Budget by Category
An extension to the budget feature, this allows the user to divide their budget based on categories. Users can
allocate parts of their budget to certain categories. Refer to the <<DeveloperGuide#Budget-Category, Developer
Guide>> for
more details.

include::../DeveloperGuide.adoc[tag=budgetPart3]



