= Winson Heng Yong Seng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ExpenseTracker

---

== Overview

This portfolio aims to document the contributions made by *Winson Heng Yong Seng* to the *ExpenseTracker*.

*ExpenseTracker* is a desktop expense tracking application developed to aid users in tracking their expenses and
save money. The user interacts with it using a Command Line Interface (CLI), and it has a Graphical User Interface
(GUI) created with JavaFX library. It is written in Java, and has about 20 kLoC.

Some of its main features are:

. Setting a budget for expenses.
. Multiple user accounts.
. Categorization of expenses.
. Statistics for expenses.


== Summary of contributions

* *Major enhancement*: added *the ability to have a budget on expenses.*
** What it does: informs the user if the their expenses exceed a set budget
** Justification: This is a core feature as it allows the user to know when they are spending too much money, the
main purpose of an expense tracker.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth
 analysis of software design alternatives. The implementation was challenging as it required changes to existing
 commands and the existing implementation of the main `ExpenseTracker` class.

* *Minor enhancement*:

. Added a `history` command that allows the user to navigate to previous commands using up/down keys.
. Added a `setRecurrenceFrequency` command that allows the user to reset their spending at a frequency of their choice.
. Added a `addCategoryBudget` command that allows the user to set budgets based on their category of expenses.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Created the organisation repository, set up issue tracker and milestones.
** Documentation:
*** Updated the About Us document template: https://github.com/CS2103-AY1819S1-T12-1/main/pull/2[#2]
*** Made changes to the Developer Guide. Improved language and edited diagrams:
https://github.com/CS2103-AY1819S1-T12-1/main/pull/74[#74]
** Community:
*** Reviewed PRs (with non-trivial review comments): https://github.com/CS2103-AY1819S1-T12-1/main/pull/6[#6],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/8[#8], https://github.com/CS2103-AY1819S1-T12-1/main/pull/9[#9],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/11[#11], https://github.com/CS2103-AY1819S1-T12-1/main/pull/20[#20],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/21[#21], https://github.com/CS2103-AY1819S1-T12-1/main/pull/22[#22],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/24[#24], https://github.com/CS2103-AY1819S1-T12-1/main/pull/31[#31],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/33[#33], https://github.com/CS2103-AY1819S1-T12-1/main/pull/45[#45],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/69[#69], https://github.com/CS2103-AY1819S1-T12-1/main/pull/71[#71],
https://github.com/CS2103-AY1819S1-T12-1/main/pull/108[#108]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=budget]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=budget]


