= [insert name] - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Student Schedule Planner

---

== Overview

Student Schedule Planner is a desktop todo-list application used to aid university students manage their tasks. User interacts with the application using CLI. The application also has a GUI created with Java FX. It is written in JAVA, which is around 10kLoC.

== Summary of contributions
*[TO BE EDITED]*

* *Major enhancement*: Major enhancement: Added archive command.
** What it does: Allows users to archive completed tasks. Archived tasks are stored in separate list, which can be viewed with command “listarchived”
** Justification: This is a necessary command for a task managing application, because users have the need to hide completed tasks, and review them in a separate list.
** Highlights:
** Credits:

* *Minor enhancement*: Added sorting feature that allows tasks to always be displayed in the order of deadline date and priority.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
** Enhancements to existing features:
** Documentation:
*** Documentation: Rewrote existing User Guide: https://github.com/CS2103-AY1819S1-T12-3/main/pull/56[#56],
https://github.com/CS2103-AY1819S1-T12-3/main/pull/69[#69], https://github.com/CS2103-AY1819S1-T12-3/main/pull/73[#73]
** Community:
** Tools:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User G
uide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
