= Tian Xueyan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TheTracker v1.3

---

== Overview

TheTracker is a desktop address book application that helps NUS students to monitor contacts, modules and events.

== Summary of contributions

* *Major enhancement*: extended AddCommand to *AddPersonCommand, AddModuleCommand, AddOccasionCommand*
** What it does: allows the user to adds Person, Module, and Occasion to their own TheTracker. Any Persons, Modules and
Occasions added by users in the command line will show in separate windows.
** Justification: These features is the basics of the product such that a user can track not onlt his or her contacts
but also modules and occasions happening in the school.

* *Major enhancement*: extended FindCommand to *FindPersonCommand, FindModuleCommand, FindOccasionCommand*
** What it does: allows the user to finds Person by name, phone, or email, or address; similarly, it allows finding
Modules by module code, module name, academic year or semester; finding occasions by occasion name, occasion date,
or occasion location.
** Justification: These features largely improve the convenience for finding a specific Person, Module or Occasion. For
instance, a Person now can be found by his or her name, phone, email or address, and multiple step of findperson command
can be used to find a person by more than one kind of conditions.
** Highlights: The finding is based on the compulsory prefixes entered by the user when he or she adds a Person, Module
or Occasion. This may be improved in TheTracker v1.4 by employing a new tagging system, which allows more dynamic
finding.

* *Minor enhancement*: built tests for Occasion related classes, and unit and system tests for the above-mentioned
commands.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]
_{give links to collated code files}_

* *Other contributions*: wrote skeleton for Occasion related UI.

** Project management:
*** Set milestones for `v1.2` - `v1.4` on GitHub
*** Opened issues for `v1.2` - `v1.4` on GitHub
** Enhancements to existing features:
*** Updated Add and Find related Commands (Pull requests https://github.com/CS2103-AY1819S1-W10-1/main/pull/94[#94],
https://github.com/CS2103-AY1819S1-W10-1/main/pull/111[#111])
*** Wrote additional tests for existing features to increase coverage(Pull requests
https://github.com/CS2103-AY1819S1-W10-1/main/pull/98[#98],
https://github.com/CS2103-AY1819S1-W10-1/main/pull/115[#115])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=add]

include::../UserGuide.adoc[tag=find]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=delete]



== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
