= Lee Yi Can - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: MeNUS

---

== Overview

*MeNUS* is an all in one restaurant management desktop application developed to help restaurant owners
and managers streamline the process of managing restaurants. It is also designed to help them
save cost from running expensive and independent systems.
// explain more

Restaurant owners interact with *MeNUS* using a Command Line Interface
(CLI). It also has a Graphical User Interface(GUI) created with https://docs.oracle.com/javafx/2/[JavaFX]. *MeNUS* is
 written using https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html[Java 9] with
approximately 30 KLOC.

== Summary of contributions
* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=yican95[RepoSense]

* *Major enhancement*: Added *Menu Management* feature
** *What it does*: Allows the user to manage the menu with the various menu management commands.
** *Justification*: It can be messy and tedious to manage menus with paper and pen. This feature help users to
streamline the process of managing the menu by allowing users to modify the menu with a single command.
** *Highlights*: This enhancement integrates with some existing sales and ingredients management commands and commands
to be added in future. It required an in-depth analysis and understanding of *MeNUS* architecture.
// Explain more

* *Minor enhancement*: Added animation to the GUI
(Pull request https://github.com/CS2103-AY1819S1-F10-4/main/pull/214[#214])
** *What it does*: Plays the https://docs.oracle.com/javafx/2/api/javafx/animation/FadeTransition
.html[FadeTransition] for a duration of 150ms when the user enters a command.

* *Other contributions*:

** Project management:
*** TBU
** Enhancements to existing features:
*** Updated the CSS theme (Pull request https://github.com/CS2103-AY1819S1-F10-4/main/pull/178[#178])
//*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests )
** Documentation:
*** Added user stories & use cases in the Developer Guide:
https://github.com/CS2103-AY1819S1-F10-4/main/pull/37[#37]
https://github.com/CS2103-AY1819S1-F10-4/main/pull/114[#114]
https://github.com/CS2103-AY1819S1-F10-4/main/pull/142[#142]
*** Added menu management features description in <<user,User Guide>> and implementation in <<dev, Developer Guide>>
** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S1-F10-4/main/pull/179[#179],
https://github.com/CS2103-AY1819S1-F10-4/main/pull/183[#183]
*** Reported bugs and suggestions for other teams in the class:
https://github.com/CS2103-AY1819S1-W16-1/main/issues/138[#138],
https://github.com/CS2103-AY1819S1-W16-1/main/issues/142[#142],
https://github.com/CS2103-AY1819S1-W16-1/main/issues/145[#145],
https://github.com/CS2103-AY1819S1-W16-1/main/issues/156[#156]

[[user]]
== Contributions to the User Guide

|===
|_The following sections below showcase my contributions to the User Guide and
my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=menu]

//include::../UserGuide.adoc[tag=menuv2]

[[dev]]
== Contributions to the Developer Guide

|===
|_The following sections below showcase my contributions to the Developer Guide. It also showcase my ability to write
technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=menuPart1]

include::../DeveloperGuide.adoc[tag=menuPart2]

include::../DeveloperGuide.adoc[tag=menuPart3]

include::../DeveloperGuide.adoc[tag=ucmenu]
