= User Guide

== Introduction

LearnV is for those who prefer to use an offline version of the dictionary for learning purposes. More importantly, LearnV is optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, LearnV can fetch the words faster than searching it on the website. Interested? Jump to the Section 2, “Quick Start” to get started. Enjoy!

== Quick Start
Ensure you have Java version 9 or later installed in your Computer.
Download the latest dictionary.jar here.
Copy the file to the folder you want to use as the home folder for LearnV
Double-click the file to start the app. The GUI should appear in a few seconds.

== Features
**Adding words**

A command for adding words to the user’s vocabulary list
Command syntax: add [word]
Format: add [word] [word] [word]

*Finding words*

Searches for a specific word from the review list and dictionary
Command syntax: find [word]
Format: find [word] [word] [word]

*List out all the words*

Displays the list of saved words by the user
Command syntax: list
Format: list

*Delete words*

Deletes a word indexed by the previously display list using the list feature
Command syntax: delete [index]
Format: delete 3

*Trivia game*

Presents a question based on words in the vocabulary list
Command syntax: trivia
Format: trivia

*Trivia Answer*
Answer the trivia question presented when using the trivia command
Command syntax: answer
Format: answer [word]

*Clears all words from the vocabulary list*

Clears all of the words on the vocabulary list.
Command syntax: clear
Format: clear

*Multilingual support*

Allow users to download dictionaries of other languages
Allows for user to enter their native language and learn English from there.
Command syntax: multi [language]
Format: multi chi

*Help view*

Displays all commands and descriptions for them
Command syntax: help
Format: help

*Exit application*

Exits the application
Command syntax: exit
Format: exit

*Group words*

Group words accordingly
Command syntax: group [word] [group]
Format: group [word] [group]

== FAQ

*Command Summary*

Add: add [word]

Find: find [word]

List: list

Delete: delete [index]

Clear: clear

Multilingual: multi

Trivia: trivia

Answer: answer [word]

Help: help

Exit: exit

Group: group [word] [group]

