# User Guide
:toc:
:toc-title:
:toclevels: 2
:sectnums:

## Features

### System Commands
#### Viewing help: `help`

Displays and explains commonly used commands. +
Format: `help`

#### Undoing the previously command: `undo`
Reverses the most recent command. +
Format: `undo`

#### Redoing the previously undone command: `redo`
Reverses the most recent undo command. +
Format: `redo`

#### Listing entered commands: `history`
Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

#### Exiting the program: `exit`
Exits the program. +
Format: `exit`

---

### Task Management

* _+Example indicates positive example_
* _-Example indicates negative example_

#### Adding a Task: `add`
[%hardbreaks]
Adds a task to the task manager.
Format:

`add n/TASK_NAME l/DUE_DATE t/PRIORITY_VALUE [d/detailed description] [l/LABEL]`

Date Format: `yyyy-mm-dd` or `yyyy-mm-dd hhmm`. A missing `hhmm` field will cause time to
be interpreted as the start of the day, i.e `00:00`.

On task creation, the task's `INDEX` is shown as such:
```
Task <INDEX>, <TASK_NAME> was created.
```
[%hardbreaks]
+Example:
`add n/complete milestone t/2018-09-14 p/99 [d/a detailed description of what needs to be done] l/CS2103` +
`add n/complete milestone t/2018-09-14 1320 p/9 [d/a detailed description of what needs to be done] l/CS2103`

-Example:
`add n/complete milestone t/2018/09/14 p/important`
`add n/complete milestone t/2018/09/14 p/-4`

#### Deleting a Task: `delete`
[%hardbreaks]
Deletes a task from the task manager
Format: `delete INDEX`
+Example: `delete 1`
-Example: `delete task`

#### Editing a Task: `edit`
[%hardbreaks]
Edits a task in the task manager
Format:
`edit INDEX [t/DUE_DATE] [p/PRIORITY_VALUE] [d/detailed description] [l/LABEL]`
+Example:
`edit 1 t/2018-09-18 d/a updated detailed description of what needs to be done`
-Example:
`edit complete milestone t/2018.09.18 d/a updated detailed description of what needs to be done`

#### Adding a dependency to a Task: `dependency`
[%hardbreaks]
Adds a dependency to a task dependant to the task dependee
Format:
`edit INDEX_DEPENDANT INDEX_DEPENDEE`
+Example:
`dependency 1 2`
-Example:
`dependency 1`
`dependency a b`

#### Completing a Task: `complete`
[%hardbreaks]
Completes task(s) in the task manager
Format: `complete INDEX` or `complete t/LABEL`
+Example:
`complete 1`
`complete l/urgent`
-Example:
`complete 1 l/urgent` (Behavior is not clear)

_Note that completion via label is case-sensitive_

* You can complete multiple tasks at once through the use of the format complete `l/LABEL`
* Note that the label needs to be valid. Validity for a label, `x`, is defined by the following
condition:
** Has at least one task which is labelled `x` and status is not "COMPLETED"

#### Listing Tasks: `list`
[%hardbreaks]
Shows a list of all tasks.

Format:
`list [f/FILTER]`, where FILTER must be any of the following:

 * `today`

 * `week`

 * `month`

 * `doable`

+Example:
`list`

+Example:
`list f/today`

-Example:
`list f/alltime`
```
1. finish math tutorial  DueDate: 01-10-18 1300 Description: before exam PriorityValue: 2 Status: IN PROGRESS
2. Attack Food  DueDate: 01-10-18 Description: what did food do PriorityValue: 88 Status: FINISHED
3. Induce Happiness DueDate: 03-10-18 Description: conditions of happiness PriorityValue: 3 Status: OVERDUE
```

#### Search for Tasks by Keyword: `find`
[%hardbreaks]
Format: `find KEYWORD`
+Example: `find complete`


## Command Summary

* System Commands
`help`
`undo`
`redo`
`history`
`exit`

* Task Management

** `add n/TASK_NAME t/DUE_DATE p/PRIORITY_VALUE [d/detailed description] [l/LABEL]`

** `delete INDEX`

** `edit INDEX [t/DUE_DATE] [p/PRIORITY_VALUE] [d/detailed description] [l/LABEL]`

** `complete INDEX` or `complete l/LABEL`

** `list`

** `find KEYWORD`
