= Cow - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:toclevels: 3
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-T09-1/main

By: `Team T09-1`      Since: `Aug 2018`      Licence: `MIT`

== Introduction

Cow is an application for those who prefer to use a desktop app for
managing tasks and contacts. It is optimized for those who prefer to
work with a Command Line Interface (CLI) while still having the benefits
of a Graphical User Interface (GUI). If you can type fast, Cow can
get your contact and task management done faster than traditional GUI
apps.

== Quick Start

1.  Ensure you have JRE 9 or later installed.
2.  Download the `.jar`.
3.  Place it in the folder where you want the data files to be stored.
4.  Type in a command and press `Enter` to execute it. For a start, type
`help` and press `Enter` to see the help text.

== Features

**Command Format**

* Words in `UPPER_CASE` are the parameters to be supplied by the user
e.g. in `add n/NAME`, `NAME` is a parameter which can be used as
`add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used
as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…` after them can be used multiple times including zero
times e.g. `[t/TAG]...` can be used as
`\` (i.e. 0 times),`t/friend`,`t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies
`n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.

[TIP]
When `INDEX` is a parameter, it refers to the index of the item shown on the task or person list

=== Viewing help: `help`

Format: `help`

=== Contacts

[NOTE]
You are allowed to have entries with the same name

==== View all contacts: `contacts list`

Format: `contacts list`

==== Add contact: `contacts add`

Format: `contacts add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]…`

==== Edit contact: `contacts edit`

Format:
`contacts edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]…`

==== Find contact: `contacts find`

Format: `contacts find KEYWORD [MORE_KEYWORDS]`

==== Delete contact: `contacts delete`

Format: `contacts delete INDEX`

// tag::assigntasktocontact[]
==== Assign tasks to contact: `contacts assign`

Format: `contacts assign c/CONTACT_INDEX k/TASK_INDEX`

==== Unassign tasks from contact: `contacts unassign`

Format: `contacts unassign c/CONTACT_INDEX k/TASK_INDEX`
// end::assigntasktocontact[]

==== Show tasks assigned to contact: `contacts assigned`

Format: `contacts assigned CONTACT_ID`

This will display all tasks assigned to the contact in the tasks pane.

=== Tasks

Format for entering dates is YYYYMMDD. Format for entering times is HHMM
in 24-hour time. (All commands from AB4 but prepend `tasks`)

[NOTE]
You are allowed to have entries with the same name

==== View all tasks: `tasks list`

Format: `tasks list`

==== Add task: `tasks add`

Format:
`tasks add n/TASK_NAME [sd/START_DATE] [st/START_TIME] ed/END_DATE et/END_TIME [t/TAG]…`

If start date or time is not entered, the missing field(s) will default to the current date/time.

==== Edit task: `tasks edit`

Format:
`tasks edit INDEX [n/TASK_NAME] [sd/START_DATE st/START_TIME ed/END_DATE et/END_TIME] [t/TAG]…`

// tag::listfindtasks[]
==== Search for task: `tasks find`

Find tasks that based on name, start date, end date and/or tags +
Format:
`tasks find [n/KEYWORD]... [sd/START_DATE] [ed/END_DATE] [t/TAG]…`

****
* Searching by keyword is case insensitive. e.g `hans` will match `Hans`
* Only full words will be matched e.g. `Han` will not match `Hans`
* Providing multiple keywords or tags will return tasks that match any of the keywords or tags.
* Searching based on different criteria will return tasks that match all criteria e.g. Searching on start date and end date
will return tasks that match both
****
// end::listfindtasks[]

==== Select a task: `tasks select`

Format: `tasks select INDEX`

Selects the task identified by the index number used in the displayed task list.


==== Delete task: `tasks delete`

Format: `tasks delete INDEX1 [INDEX2] [INDEX3] ...`

Delete all tasks corresponding to the indices provided.

// tag::tasksdeleteall[]
==== Delete all tasks: `tasks delete all`

Format: `tasks delete all`

Delete all tasks that are shown in the list.
// end::tasksdeleteall[]

// tag::assigncontacttotask[]
==== Assign person to task: `tasks assign`

Format: `tasks assign k/TASK_INDEX c/CONTACT_INDEX`

==== Unassign person from tasks: `tasks unassign`

Format: `tasks unassign k/TASK_INDEX c/CONTACT_INDEX`
// end::assigncontacttotask[]

==== Show full details of a task: `tasks assigned`

Format: `tasks assigned TASK_ID`

This will display the contacts assigned to the task in the contacts
pane.

==== Display

// tag::calendar[]

=== Calendar

Format for entering year is YYYY.
Format for entering month is MM.
Format for entering dates is YYYYMMDD.

Each cell in the calendar is populated with tasks that end on that day. Clicking on any task would cause its details to be displayed in the task details pane. Task filters applied via the `tasks find` command would also apply to the tasks displayed in the calendar.

If there are more than 5 tasks ending on that day, the cell will be scrollable, but a scroll bar is not displayed due to space constraints.
// end::calendar[]

// tag::calendarshow[]
==== View calendar for tasks due within given year and month: `calendar show`

Format: `calendar show y/YEAR m/MONTH`

This will populate the calendar panel with tasks from the specified month. Entries from the end of the previous month and the start of the following month may also be displayed depending on the length and start day of the specified month.
// end::calendarshow[]

==== List tasks for a specific day: `calendars list` `[coming in v2.0]`

Format: `calendars list ed/END_DATE`

==== Share calendar: `calendars share` `[coming in v2.0]`

Format: `calendars share CONTACT_INDEX`

=== Global

==== Undo previous command `undo`

Format: `undo`

==== Redo previously undone command `redo`

Format: `redo`

==== Exiting the program: `exit`

Format: `exit`

==== Saving data

Data is saved in the hard disk automatically after any command that
changes the data. There is no need to save manually.
